<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>3 Multilevel Modelling Practical 3 (Week 4) | MLM_worksheets.knit</title>
  <meta name="description" content="" />
  <meta name="generator" content="bookdown 0.42 and GitBook 2.6.7" />

  <meta property="og:title" content="3 Multilevel Modelling Practical 3 (Week 4) | MLM_worksheets.knit" />
  <meta property="og:type" content="book" />
  
  
  

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="3 Multilevel Modelling Practical 3 (Week 4) | MLM_worksheets.knit" />
  
  
  

<meta name="author" content="Daniele Turchetti" />



  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="multilevel-modelling-practical-2-week-3.html"/>
<link rel="next" href="multilevel-modelling-practical-4-week-5.html"/>
<script src="libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/fuse.js@6.4.6/dist/fuse.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />








<link href="libs/anchor-sections-1.1.0/anchor-sections.css" rel="stylesheet" />
<link href="libs/anchor-sections-1.1.0/anchor-sections-hash.css" rel="stylesheet" />
<script src="libs/anchor-sections-1.1.0/anchor-sections.js"></script>


<style type="text/css">
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { display: inline-block; text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { color: #008000; } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { color: #008000; font-weight: bold; } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

<style type="text/css">
  
  div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
</style>

<link rel="stylesheet" href="styles.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">Home</a></li>

<li class="divider"></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i>Welcome to multilevel modelling</a></li>
<li class="chapter" data-level="1" data-path="multilevel-modelling-practical-1-week-2.html"><a href="multilevel-modelling-practical-1-week-2.html"><i class="fa fa-check"></i><b>1</b> Multilevel Modelling Practical 1 (Week 2)</a>
<ul>
<li class="chapter" data-level="1.1" data-path="multilevel-modelling-practical-1-week-2.html"><a href="multilevel-modelling-practical-1-week-2.html#instructions-start-here"><i class="fa fa-check"></i><b>1.1</b> Instructions – start here!</a></li>
<li class="chapter" data-level="1.2" data-path="multilevel-modelling-practical-1-week-2.html"><a href="multilevel-modelling-practical-1-week-2.html#exercises-1"><i class="fa fa-check"></i><b>1.2</b> Exercises 1</a></li>
<li class="chapter" data-level="1.3" data-path="multilevel-modelling-practical-1-week-2.html"><a href="multilevel-modelling-practical-1-week-2.html#exercises-2"><i class="fa fa-check"></i><b>1.3</b> Exercises 2</a></li>
</ul></li>
<li class="chapter" data-level="2" data-path="multilevel-modelling-practical-2-week-3.html"><a href="multilevel-modelling-practical-2-week-3.html"><i class="fa fa-check"></i><b>2</b> Multilevel Modelling Practical 2 (Week 3)</a>
<ul>
<li class="chapter" data-level="2.1" data-path="multilevel-modelling-practical-2-week-3.html"><a href="multilevel-modelling-practical-2-week-3.html#instructions-start-here-1"><i class="fa fa-check"></i><b>2.1</b> Instructions – start here!</a></li>
<li class="chapter" data-level="2.2" data-path="multilevel-modelling-practical-2-week-3.html"><a href="multilevel-modelling-practical-2-week-3.html#exercises-1-1"><i class="fa fa-check"></i><b>2.2</b> Exercises 1</a>
<ul>
<li class="chapter" data-level="2.2.1" data-path="multilevel-modelling-practical-2-week-3.html"><a href="multilevel-modelling-practical-2-week-3.html#acquire-and-prepare-data"><i class="fa fa-check"></i><b>2.2.1</b> Acquire and prepare data</a></li>
<li class="chapter" data-level="2.2.2" data-path="multilevel-modelling-practical-2-week-3.html"><a href="multilevel-modelling-practical-2-week-3.html#exploratory-analysis"><i class="fa fa-check"></i><b>2.2.2</b> Exploratory analysis</a></li>
<li class="chapter" data-level="2.2.3" data-path="multilevel-modelling-practical-2-week-3.html"><a href="multilevel-modelling-practical-2-week-3.html#naive-simple-linear-regression-models"><i class="fa fa-check"></i><b>2.2.3</b> Naive simple linear regression models</a></li>
</ul></li>
<li class="chapter" data-level="2.3" data-path="multilevel-modelling-practical-2-week-3.html"><a href="multilevel-modelling-practical-2-week-3.html#exercise-2"><i class="fa fa-check"></i><b>2.3</b> Exercise 2</a></li>
<li class="chapter" data-level="2.4" data-path="multilevel-modelling-practical-2-week-3.html"><a href="multilevel-modelling-practical-2-week-3.html#exercise-3-if-time"><i class="fa fa-check"></i><b>2.4</b> Exercise 3 (if time)</a></li>
</ul></li>
<li class="chapter" data-level="3" data-path="multilevel-modelling-practical-3-week-4.html"><a href="multilevel-modelling-practical-3-week-4.html"><i class="fa fa-check"></i><b>3</b> Multilevel Modelling Practical 3 (Week 4)</a>
<ul>
<li class="chapter" data-level="3.1" data-path="multilevel-modelling-practical-3-week-4.html"><a href="multilevel-modelling-practical-3-week-4.html#instructions-start-here-2"><i class="fa fa-check"></i><b>3.1</b> Instructions – start here!</a></li>
<li class="chapter" data-level="3.2" data-path="multilevel-modelling-practical-3-week-4.html"><a href="multilevel-modelling-practical-3-week-4.html#exercise-1"><i class="fa fa-check"></i><b>3.2</b> Exercise 1</a>
<ul>
<li class="chapter" data-level="3.2.1" data-path="multilevel-modelling-practical-3-week-4.html"><a href="multilevel-modelling-practical-3-week-4.html#preparation-of-the-data-set"><i class="fa fa-check"></i><b>3.2.1</b> Preparation of the data set</a></li>
<li class="chapter" data-level="3.2.2" data-path="multilevel-modelling-practical-3-week-4.html"><a href="multilevel-modelling-practical-3-week-4.html#fitting-the-random-intercept-and-slope-model"><i class="fa fa-check"></i><b>3.2.2</b> Fitting the random intercept and slope model</a></li>
<li class="chapter" data-level="3.2.3" data-path="multilevel-modelling-practical-3-week-4.html"><a href="multilevel-modelling-practical-3-week-4.html#fitted-lines-by-class"><i class="fa fa-check"></i><b>3.2.3</b> Fitted lines by class</a></li>
<li class="chapter" data-level="3.2.4" data-path="multilevel-modelling-practical-3-week-4.html"><a href="multilevel-modelling-practical-3-week-4.html#the-intercept-only-empty-model-and-icc"><i class="fa fa-check"></i><b>3.2.4</b> The intercept-only / empty model and ICC</a></li>
<li class="chapter" data-level="3.2.5" data-path="multilevel-modelling-practical-3-week-4.html"><a href="multilevel-modelling-practical-3-week-4.html#the-random-intercept-model-with-covariate"><i class="fa fa-check"></i><b>3.2.5</b> The random intercept model (with covariate)</a></li>
</ul></li>
<li class="chapter" data-level="3.3" data-path="multilevel-modelling-practical-3-week-4.html"><a href="multilevel-modelling-practical-3-week-4.html#exercise-2-1"><i class="fa fa-check"></i><b>3.3</b> Exercise 2</a>
<ul>
<li class="chapter" data-level="3.3.1" data-path="multilevel-modelling-practical-3-week-4.html"><a href="multilevel-modelling-practical-3-week-4.html#preparation"><i class="fa fa-check"></i><b>3.3.1</b> Preparation</a></li>
<li class="chapter" data-level="3.3.2" data-path="multilevel-modelling-practical-3-week-4.html"><a href="multilevel-modelling-practical-3-week-4.html#the-random-intercept-model"><i class="fa fa-check"></i><b>3.3.2</b> The random intercept model</a></li>
<li class="chapter" data-level="3.3.3" data-path="multilevel-modelling-practical-3-week-4.html"><a href="multilevel-modelling-practical-3-week-4.html#diagnostics"><i class="fa fa-check"></i><b>3.3.3</b> Diagnostics</a></li>
<li class="chapter" data-level="3.3.4" data-path="multilevel-modelling-practical-3-week-4.html"><a href="multilevel-modelling-practical-3-week-4.html#include-a-second-fixed-effect-variable-gender"><i class="fa fa-check"></i><b>3.3.4</b> Include a second fixed effect variable: gender</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="4" data-path="multilevel-modelling-practical-4-week-5.html"><a href="multilevel-modelling-practical-4-week-5.html"><i class="fa fa-check"></i><b>4</b> Multilevel Modelling Practical 4 (Week 5)</a>
<ul>
<li class="chapter" data-level="4.1" data-path="multilevel-modelling-practical-4-week-5.html"><a href="multilevel-modelling-practical-4-week-5.html#instructions-start-here-3"><i class="fa fa-check"></i><b>4.1</b> Instructions – start here!</a></li>
<li class="chapter" data-level="4.2" data-path="multilevel-modelling-practical-4-week-5.html"><a href="multilevel-modelling-practical-4-week-5.html#exercise-1-analysis-of-the-active-time-study-data-lecture-5"><i class="fa fa-check"></i><b>4.2</b> Exercise 1: Analysis of the Active Time study data (lecture 5)</a>
<ul>
<li class="chapter" data-level="4.2.1" data-path="multilevel-modelling-practical-4-week-5.html"><a href="multilevel-modelling-practical-4-week-5.html#how-important-is-group-structure-vpcs-and-iccs"><i class="fa fa-check"></i><b>4.2.1</b> How important is group structure? (VPCs and ICCs)</a></li>
<li class="chapter" data-level="4.2.2" data-path="multilevel-modelling-practical-4-week-5.html"><a href="multilevel-modelling-practical-4-week-5.html#three-level-model-with-explanatory-variables"><i class="fa fa-check"></i><b>4.2.2</b> Three level Model with explanatory variables</a></li>
<li class="chapter" data-level="4.2.3" data-path="multilevel-modelling-practical-4-week-5.html"><a href="multilevel-modelling-practical-4-week-5.html#comparison-of-empty-model-with-model-with-explanatory-variables"><i class="fa fa-check"></i><b>4.2.3</b> Comparison of empty model with model with explanatory variables</a></li>
<li class="chapter" data-level="4.2.4" data-path="multilevel-modelling-practical-4-week-5.html"><a href="multilevel-modelling-practical-4-week-5.html#further-analysis-bottom-up-approach"><i class="fa fa-check"></i><b>4.2.4</b> Further analysis (bottom up approach)</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="5" data-path="multilevel-modelling-practical-5-week-6.html"><a href="multilevel-modelling-practical-5-week-6.html"><i class="fa fa-check"></i><b>5</b> Multilevel Modelling Practical 5 (Week 6)</a>
<ul>
<li class="chapter" data-level="5.1" data-path="multilevel-modelling-practical-5-week-6.html"><a href="multilevel-modelling-practical-5-week-6.html#instructions---start-here"><i class="fa fa-check"></i><b>5.1</b> Instructions - start here!</a>
<ul>
<li class="chapter" data-level="5.1.1" data-path="multilevel-modelling-practical-5-week-6.html"><a href="multilevel-modelling-practical-5-week-6.html#overview"><i class="fa fa-check"></i><b>5.1.1</b> Overview</a></li>
<li class="chapter" data-level="5.1.2" data-path="multilevel-modelling-practical-5-week-6.html"><a href="multilevel-modelling-practical-5-week-6.html#multilevel-modelling-with-longitudinal-data"><i class="fa fa-check"></i><b>5.1.2</b> Multilevel modelling with longitudinal data</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="6" data-path="multilevel-modelling-practical-6-week-7.html"><a href="multilevel-modelling-practical-6-week-7.html"><i class="fa fa-check"></i><b>6</b> Multilevel Modelling Practical 6 (Week 7)</a>
<ul>
<li class="chapter" data-level="6.1" data-path="multilevel-modelling-practical-6-week-7.html"><a href="multilevel-modelling-practical-6-week-7.html#instructions---start-here-1"><i class="fa fa-check"></i><b>6.1</b> Instructions - start here!</a></li>
<li class="chapter" data-level="6.2" data-path="multilevel-modelling-practical-6-week-7.html"><a href="multilevel-modelling-practical-6-week-7.html#exercise-1-long-and-wide-data-shape"><i class="fa fa-check"></i><b>6.2</b> Exercise 1 (Long and wide data shape)</a>
<ul>
<li class="chapter" data-level="6.2.1" data-path="multilevel-modelling-practical-6-week-7.html"><a href="multilevel-modelling-practical-6-week-7.html#regression-vs-multilevel-analysis"><i class="fa fa-check"></i><b>6.2.1</b> Regression vs multilevel analysis</a></li>
</ul></li>
<li class="chapter" data-level="6.3" data-path="multilevel-modelling-practical-6-week-7.html"><a href="multilevel-modelling-practical-6-week-7.html#exercise-2-simulation-from-the-two-level-longitudinal-model"><i class="fa fa-check"></i><b>6.3</b> Exercise 2 (simulation from the two-level longitudinal model)</a></li>
<li class="chapter" data-level="6.4" data-path="multilevel-modelling-practical-6-week-7.html"><a href="multilevel-modelling-practical-6-week-7.html#end-of-lab"><i class="fa fa-check"></i><b>6.4</b> End of lab!</a></li>
</ul></li>
<li class="chapter" data-level="7" data-path="multilevel-modelling-practical-7-week-8.html"><a href="multilevel-modelling-practical-7-week-8.html"><i class="fa fa-check"></i><b>7</b> Multilevel Modelling Practical 7 (Week 8)</a>
<ul>
<li class="chapter" data-level="7.1" data-path="multilevel-modelling-practical-7-week-8.html"><a href="multilevel-modelling-practical-7-week-8.html#instructions---start-here-2"><i class="fa fa-check"></i><b>7.1</b> Instructions - start here!</a></li>
<li class="chapter" data-level="7.2" data-path="multilevel-modelling-practical-7-week-8.html"><a href="multilevel-modelling-practical-7-week-8.html#exercise-1-aids-data-example-2-from-lecture-7"><i class="fa fa-check"></i><b>7.2</b> Exercise 1 (Aids data: Example 2 from lecture 7)</a></li>
<li class="chapter" data-level="7.3" data-path="multilevel-modelling-practical-7-week-8.html"><a href="multilevel-modelling-practical-7-week-8.html#exercise-2-leukaemia-data-example-3-from-lecture-7"><i class="fa fa-check"></i><b>7.3</b> Exercise 2 (Leukaemia data: Example 3 from lecture 7)</a></li>
<li class="chapter" data-level="7.4" data-path="multilevel-modelling-practical-7-week-8.html"><a href="multilevel-modelling-practical-7-week-8.html#exercise-3-toxoplasmosis-data-binomial-logistic-regression"><i class="fa fa-check"></i><b>7.4</b> Exercise 3: Toxoplasmosis data (Binomial logistic regression)</a></li>
<li class="chapter" data-level="7.5" data-path="multilevel-modelling-practical-7-week-8.html"><a href="multilevel-modelling-practical-7-week-8.html#end-of-lab-1"><i class="fa fa-check"></i><b>7.5</b> ## End of lab!</a></li>
</ul></li>
<li class="chapter" data-level="8" data-path="multilevel-modelling-practical-8-week-9.html"><a href="multilevel-modelling-practical-8-week-9.html"><i class="fa fa-check"></i><b>8</b> Multilevel Modelling Practical 8 (Week 9)</a>
<ul>
<li class="chapter" data-level="8.1" data-path="multilevel-modelling-practical-8-week-9.html"><a href="multilevel-modelling-practical-8-week-9.html#instructions---start-here-3"><i class="fa fa-check"></i><b>8.1</b> Instructions - start here!</a></li>
<li class="chapter" data-level="8.2" data-path="multilevel-modelling-practical-8-week-9.html"><a href="multilevel-modelling-practical-8-week-9.html#preliminaries"><i class="fa fa-check"></i><b>8.2</b> Preliminaries</a></li>
<li class="chapter" data-level="8.3" data-path="multilevel-modelling-practical-8-week-9.html"><a href="multilevel-modelling-practical-8-week-9.html#exercise-1-betablocker-data"><i class="fa fa-check"></i><b>8.3</b> Exercise 1: Betablocker data</a></li>
<li class="chapter" data-level="8.4" data-path="multilevel-modelling-practical-8-week-9.html"><a href="multilevel-modelling-practical-8-week-9.html#exercise-2-digging-deeper"><i class="fa fa-check"></i><b>8.4</b> Exercise 2 (digging deeper)</a></li>
<li class="chapter" data-level="8.5" data-path="multilevel-modelling-practical-8-week-9.html"><a href="multilevel-modelling-practical-8-week-9.html#exercise-3-optional-toxoplasmosis-data-revisited"><i class="fa fa-check"></i><b>8.5</b> Exercise 3 (optional): Toxoplasmosis data revisited</a></li>
<li class="chapter" data-level="8.6" data-path="multilevel-modelling-practical-8-week-9.html"><a href="multilevel-modelling-practical-8-week-9.html#summative-assessment"><i class="fa fa-check"></i><b>8.6</b> Summative assessment</a></li>
<li class="chapter" data-level="8.7" data-path="multilevel-modelling-practical-8-week-9.html"><a href="multilevel-modelling-practical-8-week-9.html#end-of-lab-2"><i class="fa fa-check"></i><b>8.7</b> ## End of lab!</a></li>
</ul></li>
<li class="chapter" data-level="9" data-path="multilevel-modelling-practical-9-week-10.html"><a href="multilevel-modelling-practical-9-week-10.html"><i class="fa fa-check"></i><b>9</b> Multilevel Modelling Practical 9 (Week 10)</a>
<ul>
<li class="chapter" data-level="9.1" data-path="multilevel-modelling-practical-9-week-10.html"><a href="multilevel-modelling-practical-9-week-10.html#dealing-with-missing-values"><i class="fa fa-check"></i><b>9.1</b> Dealing with missing values</a></li>
</ul></li>
</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./"></a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="multilevel-modelling-practical-3-week-4" class="section level1 hasAnchor" number="3">
<h1><span class="header-section-number">3</span> Multilevel Modelling Practical 3 (Week 4)<a href="multilevel-modelling-practical-3-week-4.html#multilevel-modelling-practical-3-week-4" class="anchor-section" aria-label="Anchor link to header"></a></h1>
<div id="instructions-start-here-2" class="section level2 hasAnchor" number="3.1">
<h2><span class="header-section-number">3.1</span> Instructions – start here!<a href="multilevel-modelling-practical-3-week-4.html#instructions-start-here-2" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p><strong>Exercise 1</strong> takes you through the analysis carried out in Lecture 4 of this module. <strong>Exercise 2</strong> allows you to produce some additional analysis using the 1982 High School and Beyond Survey data introduced in the previous practical.</p>
<p>We initially load the R packages <em>haven</em>, <em>ggplot2</em>, <em>lme4</em> and <em>lmerTest</em>. Further R packages will be loaded where needed.</p>
<div class="sourceCode" id="cb181"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb181-1"><a href="multilevel-modelling-practical-3-week-4.html#cb181-1" tabindex="-1"></a><span class="fu">require</span>(haven)      <span class="co"># to load the SPSS .sav file</span></span>
<span id="cb181-2"><a href="multilevel-modelling-practical-3-week-4.html#cb181-2" tabindex="-1"></a><span class="fu">require</span>(ggplot2)    <span class="co"># used for production of graphs</span></span>
<span id="cb181-3"><a href="multilevel-modelling-practical-3-week-4.html#cb181-3" tabindex="-1"></a><span class="fu">require</span>(lme4)       <span class="co"># used for fitting random effect models</span></span>
<span id="cb181-4"><a href="multilevel-modelling-practical-3-week-4.html#cb181-4" tabindex="-1"></a><span class="fu">require</span>(lmerTest)   <span class="co"># used in hypothesis testing</span></span></code></pre></div>
</div>
<div id="exercise-1" class="section level2 hasAnchor" number="3.2">
<h2><span class="header-section-number">3.2</span> Exercise 1<a href="multilevel-modelling-practical-3-week-4.html#exercise-1" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>This is a continuation of Exercise 1 from the previous practical. Last week, we considered an exploratory analysis of the student popularity data set. We will now consider a two-level multilevel model for the response variable (popularity, <span class="math inline">\(y\)</span>) using the extraversion covariate (<span class="math inline">\(x\)</span>).</p>
<div id="preparation-of-the-data-set" class="section level3 hasAnchor" number="3.2.1">
<h3><span class="header-section-number">3.2.1</span> Preparation of the data set<a href="multilevel-modelling-practical-3-week-4.html#preparation-of-the-data-set" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>We prepare the data as previously:</p>
<div class="sourceCode" id="cb182"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb182-1"><a href="multilevel-modelling-practical-3-week-4.html#cb182-1" tabindex="-1"></a>pop.rawdata <span class="ot">&lt;-</span> </span>
<span id="cb182-2"><a href="multilevel-modelling-practical-3-week-4.html#cb182-2" tabindex="-1"></a>  <span class="fu">read_sav</span>(<span class="at">file=</span><span class="st">&quot;https://github.com/MultiLevelAnalysis/Datasets-third-edition-Multilevel-book/blob/master/chapter%202/popularity/SPSS/popular2.sav?raw=true&quot;</span>)</span></code></pre></div>
<p>Re-label some columns as before:</p>
<div class="sourceCode" id="cb183"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb183-1"><a href="multilevel-modelling-practical-3-week-4.html#cb183-1" tabindex="-1"></a>pop.data <span class="ot">&lt;-</span> pop.rawdata[,<span class="fu">c</span>(<span class="st">&quot;pupil&quot;</span>, <span class="st">&quot;class&quot;</span>, <span class="st">&quot;extrav&quot;</span>, <span class="st">&quot;sex&quot;</span>, <span class="st">&quot;texp&quot;</span>, <span class="st">&quot;popular&quot;</span>)]</span>
<span id="cb183-2"><a href="multilevel-modelling-practical-3-week-4.html#cb183-2" tabindex="-1"></a></span>
<span id="cb183-3"><a href="multilevel-modelling-practical-3-week-4.html#cb183-3" tabindex="-1"></a><span class="fu">colnames</span>(pop.data)<span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">&quot;pupil&quot;</span>, <span class="st">&quot;class&quot;</span>, <span class="st">&quot;extraversion&quot;</span>, <span class="st">&quot;gender&quot;</span>, <span class="st">&quot;experience&quot;</span>, <span class="st">&quot;popularity&quot;</span>)</span>
<span id="cb183-4"><a href="multilevel-modelling-practical-3-week-4.html#cb183-4" tabindex="-1"></a></span>
<span id="cb183-5"><a href="multilevel-modelling-practical-3-week-4.html#cb183-5" tabindex="-1"></a><span class="fu">head</span>(pop.data) <span class="co"># we have a look at the first 6 observations</span></span></code></pre></div>
<pre><code>## # A tibble: 6 × 6
##   pupil class extraversion gender    experience popularity
##   &lt;dbl&gt; &lt;dbl&gt;        &lt;dbl&gt; &lt;dbl+lbl&gt;      &lt;dbl&gt;      &lt;dbl&gt;
## 1     1     1            5 1 [girl]          24        6.3
## 2     2     1            7 0 [boy]           24        4.9
## 3     3     1            4 1 [girl]          24        5.3
## 4     4     1            3 1 [girl]          24        4.7
## 5     5     1            5 1 [girl]          24        6  
## 6     6     1            4 0 [boy]           24        4.7</code></pre>
<p><span class="math inline">\(~\)</span></p>
</div>
<div id="fitting-the-random-intercept-and-slope-model" class="section level3 hasAnchor" number="3.2.2">
<h3><span class="header-section-number">3.2.2</span> Fitting the random intercept and slope model<a href="multilevel-modelling-practical-3-week-4.html#fitting-the-random-intercept-and-slope-model" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>The model takes the form</p>
<p><span class="math display">\[y_{ij}=a + b x_{ij} + u_j +v_j x_{ij} +\epsilon_{ij} \]</span>
where <span class="math inline">\(u_j\sim N(0,\sigma^2_u)\)</span>, <span class="math inline">\(v_j \sim N(0,\sigma^2_v)\)</span> and the independent error terms are <span class="math inline">\(\epsilon_{ij} \sim N(0,\sigma^2)\)</span>.</p>
<p>The following is the code to fit a random intercept and slope model (and summarise):</p>
<div class="sourceCode" id="cb185"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb185-1"><a href="multilevel-modelling-practical-3-week-4.html#cb185-1" tabindex="-1"></a>model1 <span class="ot">&lt;-</span> <span class="fu">lmer</span>(<span class="at">formula =</span> popularity <span class="sc">~</span>  <span class="dv">1</span><span class="sc">+</span> extraversion <span class="sc">+</span>(<span class="dv">1</span><span class="sc">+</span> extraversion<span class="sc">|</span>class), <span class="at">data =</span> pop.data) </span></code></pre></div>
<pre><code>## Warning in checkConv(attr(opt, &quot;derivs&quot;), opt$par, ctrl = control$checkConv, : Model failed to converge with
## max|grad| = 0.00663866 (tol = 0.002, component 1)</code></pre>
<div class="sourceCode" id="cb187"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb187-1"><a href="multilevel-modelling-practical-3-week-4.html#cb187-1" tabindex="-1"></a><span class="fu">summary</span>(model1)</span></code></pre></div>
<pre><code>## Linear mixed model fit by REML. t-tests use Satterthwaite&#39;s method [&#39;lmerModLmerTest&#39;]
## Formula: popularity ~ 1 + extraversion + (1 + extraversion | class)
##    Data: pop.data
## 
## REML criterion at convergence: 5779.4
## 
## Scaled residuals: 
##     Min      1Q  Median      3Q     Max 
## -3.1961 -0.7291  0.0145  0.6817  3.2216 
## 
## Random effects:
##  Groups   Name         Variance Std.Dev. Corr 
##  class    (Intercept)  2.99680  1.7311        
##           extraversion 0.02595  0.1611   -0.97
##  Residual              0.89495  0.9460        
## Number of obs: 2000, groups:  class, 100
## 
## Fixed effects:
##              Estimate Std. Error       df t value Pr(&gt;|t|)    
## (Intercept)   2.46106    0.20309 96.71010   12.12   &lt;2e-16 ***
## extraversion  0.49286    0.02545 89.75489   19.36   &lt;2e-16 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Correlation of Fixed Effects:
##             (Intr)
## extraversin -0.917
## optimizer (nloptwrap) convergence code: 0 (OK)
## Model failed to converge with max|grad| = 0.00663866 (tol = 0.002, component 1)</code></pre>
<p>Note the warning message about potential lack of convergence. A better optimiser should solve this issue:</p>
<div class="sourceCode" id="cb189"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb189-1"><a href="multilevel-modelling-practical-3-week-4.html#cb189-1" tabindex="-1"></a>model1 <span class="ot">&lt;-</span> <span class="fu">lmer</span>(<span class="at">formula =</span> popularity <span class="sc">~</span>  <span class="dv">1</span><span class="sc">+</span> extraversion <span class="sc">+</span>(<span class="dv">1</span><span class="sc">+</span> extraversion<span class="sc">|</span>class), <span class="at">data =</span> pop.data, <span class="at">control =</span> <span class="fu">lmerControl</span>(<span class="at">optimizer =</span><span class="st">&quot;Nelder_Mead&quot;</span>)) </span>
<span id="cb189-2"><a href="multilevel-modelling-practical-3-week-4.html#cb189-2" tabindex="-1"></a><span class="fu">summary</span>(model1)</span></code></pre></div>
<p>If you execute the above code chunk, you’ll see that the difference in estimated coefficients is very small (typically 4th decimal place) making us less concerned about the initial warning.</p>
<p><strong>TASK:</strong> Interpret the summarised model output.</p>
<details>
<summary>
Click for solution
</summary>
<ul>
<li>The expected popularity rises by 0.49286 per extra point of extraversion.</li>
<li>There is considerable variation between classes: The random effect variances are <span class="math inline">\(\sigma^2_u=2.9968\)</span> and <span class="math inline">\(\sigma^2_v=0.02595\)</span>.</li>
<li>The random effects are strongly negatively correlated (-0.97): For classes where the popularity is generally larger, increasing extraversion will have less additional effect.</li>
</ul>
</details>
<p><span class="math inline">\(~\)</span></p>
</div>
<div id="fitted-lines-by-class" class="section level3 hasAnchor" number="3.2.3">
<h3><span class="header-section-number">3.2.3</span> Fitted lines by class<a href="multilevel-modelling-practical-3-week-4.html#fitted-lines-by-class" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>The following R code plots the fitted regression lines for each class.</p>
<div class="sourceCode" id="cb190"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb190-1"><a href="multilevel-modelling-practical-3-week-4.html#cb190-1" tabindex="-1"></a>pop.data<span class="sc">$</span>pred1 <span class="ot">&lt;-</span> <span class="fu">predict</span>(model1)</span>
<span id="cb190-2"><a href="multilevel-modelling-practical-3-week-4.html#cb190-2" tabindex="-1"></a></span>
<span id="cb190-3"><a href="multilevel-modelling-practical-3-week-4.html#cb190-3" tabindex="-1"></a><span class="fu">ggplot</span>(pop.data, </span>
<span id="cb190-4"><a href="multilevel-modelling-practical-3-week-4.html#cb190-4" tabindex="-1"></a>       <span class="fu">aes</span>(<span class="at">x=</span> extraversion, <span class="at">y =</span> popularity, <span class="at">col =</span> class, <span class="at">group =</span> class))<span class="sc">+</span></span>
<span id="cb190-5"><a href="multilevel-modelling-practical-3-week-4.html#cb190-5" tabindex="-1"></a>       <span class="fu">geom_line</span>(<span class="fu">aes</span>(<span class="at">y=</span>pred1, <span class="at">group=</span>class, <span class="at">col=</span>class)) <span class="sc">+</span></span>
<span id="cb190-6"><a href="multilevel-modelling-practical-3-week-4.html#cb190-6" tabindex="-1"></a>       <span class="fu">scale_color_gradientn</span>(<span class="at">colours =</span> <span class="fu">rainbow</span>(<span class="dv">100</span>)) </span></code></pre></div>
<p><img src="MLM_worksheets_files/figure-html/unnamed-chunk-66-1.png" width="672" /></p>
<p><strong>TASK:</strong> Predicted values are given by</p>
<p><span class="math display">\[\hat{y}_{ij}=\hat{a}+\hat{b}x_{ij}+\hat{u}_j+\hat{v}_jx_{ij}\]</span>.</p>
<p>The first fitted value is <span class="math inline">\(\hat{y}_{11}=\)</span> 5.1311949. By using <code>fixef</code> to extract the fixed effects <span class="math inline">\(\hat{a}\)</span> and <span class="math inline">\(\hat{b}\)</span>, and <code>ranef</code> to extract the random effects <span class="math inline">\(\hat{u}_1\)</span> and <span class="math inline">\(\hat{v}_1\)</span>, directly calculate <span class="math inline">\(\hat{y}_{11}\)</span> and make sure it agrees with the above value.</p>
<details>
<summary>
Click for solution
</summary>
<div class="sourceCode" id="cb191"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb191-1"><a href="multilevel-modelling-practical-3-week-4.html#cb191-1" tabindex="-1"></a>fix <span class="ot">&lt;-</span> <span class="fu">as.numeric</span>(<span class="fu">fixef</span>(model1))</span>
<span id="cb191-2"><a href="multilevel-modelling-practical-3-week-4.html#cb191-2" tabindex="-1"></a>ranef1 <span class="ot">&lt;-</span> <span class="fu">as.numeric</span>(<span class="fu">ranef</span>(model1)<span class="sc">$</span>class[<span class="dv">1</span>,])</span>
<span id="cb191-3"><a href="multilevel-modelling-practical-3-week-4.html#cb191-3" tabindex="-1"></a>newx <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="dv">1</span>, pop.data<span class="sc">$</span>extraversion[<span class="dv">1</span>])</span>
<span id="cb191-4"><a href="multilevel-modelling-practical-3-week-4.html#cb191-4" tabindex="-1"></a>fix<span class="sc">%*%</span>newx <span class="sc">+</span>ranef1<span class="sc">%*%</span>newx</span></code></pre></div>
<pre><code>##          [,1]
## [1,] 5.131195</code></pre>
</details>
<p><span class="math inline">\(~\)</span></p>
</div>
<div id="the-intercept-only-empty-model-and-icc" class="section level3 hasAnchor" number="3.2.4">
<h3><span class="header-section-number">3.2.4</span> The intercept-only / empty model and ICC<a href="multilevel-modelling-practical-3-week-4.html#the-intercept-only-empty-model-and-icc" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Recall that the empty model is</p>
<p><span class="math display">\[y_{ij}=\gamma_0 + u_j +\epsilon_{ij}\]</span></p>
<p>The following code fits the empty model and summarises output.</p>
<div class="sourceCode" id="cb193"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb193-1"><a href="multilevel-modelling-practical-3-week-4.html#cb193-1" tabindex="-1"></a>intercept.only.model <span class="ot">&lt;-</span> <span class="fu">lmer</span>(<span class="at">formula =</span> popularity <span class="sc">~</span> <span class="dv">1</span> <span class="sc">+</span> (<span class="dv">1</span><span class="sc">|</span>class),<span class="at">data    =</span> pop.data) </span>
<span id="cb193-2"><a href="multilevel-modelling-practical-3-week-4.html#cb193-2" tabindex="-1"></a><span class="fu">summary</span>(intercept.only.model)  </span></code></pre></div>
<pre><code>## Linear mixed model fit by REML. t-tests use Satterthwaite&#39;s method [&#39;lmerModLmerTest&#39;]
## Formula: popularity ~ 1 + (1 | class)
##    Data: pop.data
## 
## REML criterion at convergence: 6330.5
## 
## Scaled residuals: 
##     Min      1Q  Median      3Q     Max 
## -3.5655 -0.6975  0.0020  0.6758  3.3175 
## 
## Random effects:
##  Groups   Name        Variance Std.Dev.
##  class    (Intercept) 0.7021   0.8379  
##  Residual             1.2218   1.1053  
## Number of obs: 2000, groups:  class, 100
## 
## Fixed effects:
##             Estimate Std. Error       df t value Pr(&gt;|t|)    
## (Intercept)  5.07786    0.08739 98.90973    58.1   &lt;2e-16 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
<p><strong>TASK:</strong> Calculate and interpret the intra-class correlation (ICC).</p>
<details>
<summary>
Click for solution
</summary>
<p>Method 1: read off the estimates of <span class="math inline">\(\sigma^2_u\)</span> and <span class="math inline">\(\sigma^2\)</span> from the output above.</p>
<div class="sourceCode" id="cb195"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb195-1"><a href="multilevel-modelling-practical-3-week-4.html#cb195-1" tabindex="-1"></a>rho<span class="ot">=</span> <span class="fl">0.7021</span><span class="sc">/</span>(<span class="fl">0.7021+1.2218</span>)</span>
<span id="cb195-2"><a href="multilevel-modelling-practical-3-week-4.html#cb195-2" tabindex="-1"></a>rho</span></code></pre></div>
<pre><code>## [1] 0.3649358</code></pre>
<p>Method 2: extract the relevant estimates directly:</p>
<div class="sourceCode" id="cb197"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb197-1"><a href="multilevel-modelling-practical-3-week-4.html#cb197-1" tabindex="-1"></a>vars <span class="ot">&lt;-</span> <span class="fu">as.data.frame</span>(<span class="fu">summary</span>(intercept.only.model)<span class="sc">$</span>varcor)<span class="sc">$</span>vcov</span>
<span id="cb197-2"><a href="multilevel-modelling-practical-3-week-4.html#cb197-2" tabindex="-1"></a>(rho <span class="ot">&lt;-</span> vars[<span class="dv">1</span>]<span class="sc">/</span><span class="fu">sum</span>(vars))</span></code></pre></div>
<pre><code>## [1] 0.3649386</code></pre>
<p>Method 3: the following package can also be used to calculate ICC.</p>
<div class="sourceCode" id="cb199"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb199-1"><a href="multilevel-modelling-practical-3-week-4.html#cb199-1" tabindex="-1"></a><span class="fu">require</span>(performance)</span>
<span id="cb199-2"><a href="multilevel-modelling-practical-3-week-4.html#cb199-2" tabindex="-1"></a><span class="co"># https://easystats.github.io/performance/reference/icc.html</span></span>
<span id="cb199-3"><a href="multilevel-modelling-practical-3-week-4.html#cb199-3" tabindex="-1"></a><span class="fu">icc</span>(intercept.only.model)</span></code></pre></div>
<pre><code>## # Intraclass Correlation Coefficient
## 
##     Adjusted ICC: 0.365
##   Unadjusted ICC: 0.365</code></pre>
</details>
<p><span class="math inline">\(~\)</span></p>
</div>
<div id="the-random-intercept-model-with-covariate" class="section level3 hasAnchor" number="3.2.5">
<h3><span class="header-section-number">3.2.5</span> The random intercept model (with covariate)<a href="multilevel-modelling-practical-3-week-4.html#the-random-intercept-model-with-covariate" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Now let’s look at the random intercept model with a fixed effect for extraversion. The model is</p>
<p><span class="math display">\[y_{ij}=a+b x_{ij}+u_j+\epsilon_{ij}\]</span></p>
<p>We can fit and summarise via:</p>
<div class="sourceCode" id="cb201"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb201-1"><a href="multilevel-modelling-practical-3-week-4.html#cb201-1" tabindex="-1"></a>model0 <span class="ot">&lt;-</span> <span class="fu">lmer</span>(<span class="at">formula =</span> popularity <span class="sc">~</span>  <span class="dv">1</span><span class="sc">+</span> extraversion <span class="sc">+</span>(<span class="dv">1</span><span class="sc">|</span>class), <span class="at">data    =</span> pop.data) </span>
<span id="cb201-2"><a href="multilevel-modelling-practical-3-week-4.html#cb201-2" tabindex="-1"></a><span class="fu">summary</span>(model0)</span></code></pre></div>
<pre><code>## Linear mixed model fit by REML. t-tests use Satterthwaite&#39;s method [&#39;lmerModLmerTest&#39;]
## Formula: popularity ~ 1 + extraversion + (1 | class)
##    Data: pop.data
## 
## REML criterion at convergence: 5832.6
## 
## Scaled residuals: 
##     Min      1Q  Median      3Q     Max 
## -3.0644 -0.7267  0.0165  0.7088  3.3587 
## 
## Random effects:
##  Groups   Name        Variance Std.Dev.
##  class    (Intercept) 0.8406   0.9168  
##  Residual             0.9304   0.9646  
## Number of obs: 2000, groups:  class, 100
## 
## Fixed effects:
##               Estimate Std. Error        df t value Pr(&gt;|t|)    
## (Intercept)  2.542e+00  1.411e-01 4.380e+02   18.01   &lt;2e-16 ***
## extraversion 4.863e-01  2.015e-02 1.965e+03   24.13   &lt;2e-16 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Correlation of Fixed Effects:
##             (Intr)
## extraversin -0.745</code></pre>
<p><strong>TASK:</strong> Add a column to the <code>pop.data</code> data frame called <code>pred0</code> containing the predicted responses from this model. Hence, produce a plot of the regression lines (obtained from this model) for each class (also coloured by class).</p>
<details>
<summary>
Click for solution
</summary>
<p>The following R code generates predicred responses and plots the fitted regression lines for each class.</p>
<div class="sourceCode" id="cb203"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb203-1"><a href="multilevel-modelling-practical-3-week-4.html#cb203-1" tabindex="-1"></a>pop.data<span class="sc">$</span>pred0 <span class="ot">&lt;-</span> <span class="fu">predict</span>(model0)</span>
<span id="cb203-2"><a href="multilevel-modelling-practical-3-week-4.html#cb203-2" tabindex="-1"></a></span>
<span id="cb203-3"><a href="multilevel-modelling-practical-3-week-4.html#cb203-3" tabindex="-1"></a><span class="fu">ggplot</span>(pop.data, </span>
<span id="cb203-4"><a href="multilevel-modelling-practical-3-week-4.html#cb203-4" tabindex="-1"></a>       <span class="fu">aes</span>(<span class="at">x=</span> extraversion, <span class="at">y =</span> popularity, <span class="at">col =</span> class, <span class="at">group =</span> class))<span class="sc">+</span></span>
<span id="cb203-5"><a href="multilevel-modelling-practical-3-week-4.html#cb203-5" tabindex="-1"></a>       <span class="fu">geom_line</span>(<span class="fu">aes</span>(<span class="at">y=</span>pred0, <span class="at">group=</span>class, <span class="at">col=</span>class)) <span class="sc">+</span></span>
<span id="cb203-6"><a href="multilevel-modelling-practical-3-week-4.html#cb203-6" tabindex="-1"></a>       <span class="fu">scale_color_gradientn</span>(<span class="at">colours =</span> <span class="fu">rainbow</span>(<span class="dv">100</span>)) </span></code></pre></div>
<p><img src="MLM_worksheets_files/figure-html/unnamed-chunk-73-1.png" width="672" /></p>
Notice that all the slopes are the same, as expected! Whether or not random slopes are needed (and how we decide this) will be explored later in the course.
</details>
<p><span class="math inline">\(~\)</span></p>
<p><strong>Harder (deeper thinking):</strong> please spend at least 15 mins thinking about the following before uncovering the solution details (talk also to each other and the instructor about it).</p>
<p>We have a class level covariate - teacher experience. How can we include this in the model above (random intercept model)? One possibility is to try to use this covariate to explain some of the variation in the random intercept values.</p>
<p>The random intercept model has <span class="math inline">\(a_j=a+u_j\)</span> where <span class="math inline">\(u_j\sim N(0,\sigma^2_u)\)</span>. Let <span class="math inline">\(\text{exp}_j\)</span> denote teacher experience (in years) for class <span class="math inline">\(j\)</span>. How should we modify <span class="math inline">\(a_j\)</span> to include the <span class="math inline">\(\text{exp}\)</span> covariate? Write out the resulting model in the form <span class="math inline">\(y_{ij}= \ldots\)</span> and fit the model in R. Is the experience covariate needed?</p>
<details>
<summary>
Click for solution
</summary>
<p>“Regress” the <span class="math inline">\(a_j\)</span> on <span class="math inline">\(\text{exp}\)</span> to give</p>
<p><span class="math display">\[a_j = a + \alpha \text{exp}_j +u_j\]</span>
where <span class="math inline">\(u_j\sim N(0,\sigma^2_u)\)</span>. Hence, the full model becomes</p>
<p><span class="math display">\[y_{ij}=a +\alpha \text{exp}_j + b x_{ij} + u_j + \epsilon_{ij} \]</span>
We can fit this model in R via:</p>
<div class="sourceCode" id="cb204"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb204-1"><a href="multilevel-modelling-practical-3-week-4.html#cb204-1" tabindex="-1"></a>model2 <span class="ot">&lt;-</span> <span class="fu">lmer</span>(<span class="at">formula =</span> popularity <span class="sc">~</span>  <span class="dv">1</span><span class="sc">+</span> extraversion <span class="sc">+</span> experience <span class="sc">+</span>(<span class="dv">1</span><span class="sc">|</span>class), <span class="at">data    =</span> pop.data) </span>
<span id="cb204-2"><a href="multilevel-modelling-practical-3-week-4.html#cb204-2" tabindex="-1"></a><span class="fu">summary</span>(model2)</span></code></pre></div>
<pre><code>## Linear mixed model fit by REML. t-tests use Satterthwaite&#39;s method [&#39;lmerModLmerTest&#39;]
## Formula: popularity ~ 1 + extraversion + experience + (1 | class)
##    Data: pop.data
## 
## REML criterion at convergence: 5776.2
## 
## Scaled residuals: 
##     Min      1Q  Median      3Q     Max 
## -3.2000 -0.7193  0.0211  0.6995  3.3732 
## 
## Random effects:
##  Groups   Name        Variance Std.Dev.
##  class    (Intercept) 0.4251   0.6520  
##  Residual             0.9303   0.9645  
## Number of obs: 2000, groups:  class, 100
## 
## Fixed effects:
##               Estimate Std. Error        df t value Pr(&gt;|t|)    
## (Intercept)  1.035e+00  2.076e-01 2.381e+02   4.985 1.19e-06 ***
## extraversion 5.037e-01  2.017e-02 1.962e+03  24.976  &lt; 2e-16 ***
## experience   9.910e-02  1.056e-02 1.018e+02   9.385 1.90e-15 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Correlation of Fixed Effects:
##             (Intr) extrvr
## extraversin -0.610       
## experience  -0.799  0.142</code></pre>
A test of the null hypothesis that <span class="math inline">\(\alpha=0\)</span> (after adjusting for extraversion) would be rejected (easily) at the <span class="math inline">\(5\%\)</span> level. It looks like the experience covariate is needed here.
</details>
<p><span class="math inline">\(~\)</span></p>
<p><strong>Even deeper:</strong> The random intercept and slope model has <span class="math inline">\(b_j=b+v_j\)</span> where <span class="math inline">\(v_j\sim N(0,\sigma^2_v)\)</span>. How should we modify <span class="math inline">\(b_j\)</span> to include the <span class="math inline">\(\text{exp}\)</span> covariate? Write out the resulting model in the form <span class="math inline">\(y_{ij}= \ldots\)</span>. If done correctly, this should give an interaction term of the form <span class="math inline">\(\text{exp}_j x_{ij}\)</span>.</p>
<p><span class="math inline">\(~\)</span></p>
</div>
</div>
<div id="exercise-2-1" class="section level2 hasAnchor" number="3.3">
<h2><span class="header-section-number">3.3</span> Exercise 2<a href="multilevel-modelling-practical-3-week-4.html#exercise-2-1" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<div id="preparation" class="section level3 hasAnchor" number="3.3.1">
<h3><span class="header-section-number">3.3.1</span> Preparation<a href="multilevel-modelling-practical-3-week-4.html#preparation" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>This is a continuation of Exercise 3 from the previous practical.</p>
<p>We continue now with the analysis of the Maths achievement scores from the 1982 High School and Beyond Survey. As on the last worksheet, load the data into your workspace via:</p>
<div class="sourceCode" id="cb206"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb206-1"><a href="multilevel-modelling-practical-3-week-4.html#cb206-1" tabindex="-1"></a>sub_hsb <span class="ot">&lt;-</span> </span>
<span id="cb206-2"><a href="multilevel-modelling-practical-3-week-4.html#cb206-2" tabindex="-1"></a>   <span class="fu">read.csv</span>(<span class="at">file=</span><span class="st">&quot;https://andygolightly.github.io/teaching/MATH43515/sub_hsb.csv&quot;</span>)</span></code></pre></div>
<p>Carry out the following operations for simple access of variables.</p>
<div class="sourceCode" id="cb207"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb207-1"><a href="multilevel-modelling-practical-3-week-4.html#cb207-1" tabindex="-1"></a>data <span class="ot">&lt;-</span> sub_hsb</span>
<span id="cb207-2"><a href="multilevel-modelling-practical-3-week-4.html#cb207-2" tabindex="-1"></a>mathach <span class="ot">&lt;-</span> data<span class="sc">$</span>mathach <span class="co"># Maths achievement score (response)</span></span>
<span id="cb207-3"><a href="multilevel-modelling-practical-3-week-4.html#cb207-3" tabindex="-1"></a>ses <span class="ot">&lt;-</span> data<span class="sc">$</span>ses</span>
<span id="cb207-4"><a href="multilevel-modelling-practical-3-week-4.html#cb207-4" tabindex="-1"></a>female <span class="ot">&lt;-</span> data<span class="sc">$</span>female</span>
<span id="cb207-5"><a href="multilevel-modelling-practical-3-week-4.html#cb207-5" tabindex="-1"></a>school.f <span class="ot">&lt;-</span> <span class="fu">as.factor</span>(data<span class="sc">$</span>schid) <span class="co">#I&#39;m using .f for factor in the variable name</span></span>
<span id="cb207-6"><a href="multilevel-modelling-practical-3-week-4.html#cb207-6" tabindex="-1"></a><span class="fu">colnames</span>(data)</span></code></pre></div>
<pre><code>## [1] &quot;schid&quot;    &quot;minority&quot; &quot;female&quot;   &quot;ses&quot;      &quot;mathach&quot;  &quot;size&quot;     &quot;schtype&quot;  &quot;meanses&quot;</code></pre>
<p>Recall that the full dataset can be found within the package <a href="https://rdrr.io/cran/merTools/man/hsb.html">merTools</a>. Click the link to read about the data set.</p>
<p><span class="math inline">\(~\)</span></p>
</div>
<div id="the-random-intercept-model" class="section level3 hasAnchor" number="3.3.2">
<h3><span class="header-section-number">3.3.2</span> The random intercept model<a href="multilevel-modelling-practical-3-week-4.html#the-random-intercept-model" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>As in Exercise 1, to specify random effects, apply the same formula as that for linear regression using the function <code>lmer</code> instead of <code>lm</code>. We begin with the random intercept model, including a fixed effect for <code>ses</code> (a measure of socio-economic status).</p>
<p>A random intercept for the upper level (in this case, school) will be coded as <code>(1|school.f)</code>.</p>
<div class="sourceCode" id="cb209"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb209-1"><a href="multilevel-modelling-practical-3-week-4.html#cb209-1" tabindex="-1"></a>model.rint <span class="ot">&lt;-</span> <span class="fu">lmer</span>(mathach <span class="sc">~</span> ses <span class="sc">+</span> (<span class="dv">1</span> <span class="sc">|</span> school.f), <span class="at">data=</span>data)</span>
<span id="cb209-2"><a href="multilevel-modelling-practical-3-week-4.html#cb209-2" tabindex="-1"></a><span class="fu">summary</span>(model.rint)</span></code></pre></div>
<pre><code>## Linear mixed model fit by REML. t-tests use Satterthwaite&#39;s method [&#39;lmerModLmerTest&#39;]
## Formula: mathach ~ ses + (1 | school.f)
##    Data: data
## 
## REML criterion at convergence: 8601
## 
## Scaled residuals: 
##      Min       1Q   Median       3Q      Max 
## -2.81268 -0.70959 -0.03616  0.76678  2.74101 
## 
## Random effects:
##  Groups   Name        Variance Std.Dev.
##  school.f (Intercept)  6.339   2.518   
##  Residual             36.119   6.010   
## Number of obs: 1329, groups:  school.f, 30
## 
## Fixed effects:
##              Estimate Std. Error        df t value Pr(&gt;|t|)    
## (Intercept)   12.8865     0.4908   26.4805  26.256   &lt;2e-16 ***
## ses            2.1202     0.2536 1234.9858   8.359   &lt;2e-16 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Correlation of Fixed Effects:
##     (Intr)
## ses -0.010</code></pre>
<p><strong>TASK:</strong> Interpret the output, find the ICC.</p>
<p><span class="math inline">\(~\)</span></p>
<p>We now extract and visualize fitted values vs. the linear model: to do this with <code>ggplot</code>, add the main plot (<code>ggplot(...)</code>) including a line (<code>geom_line()</code>) indicating the predictions acquired from <code>predict(Model1)</code> and the grouping structure (school). Note that <code>geom_point()</code> includes the data points for reference.</p>
<div class="sourceCode" id="cb211"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb211-1"><a href="multilevel-modelling-practical-3-week-4.html#cb211-1" tabindex="-1"></a>data<span class="sc">$</span>pred1 <span class="ot">&lt;-</span> <span class="fu">predict</span>(model.rint)</span>
<span id="cb211-2"><a href="multilevel-modelling-practical-3-week-4.html#cb211-2" tabindex="-1"></a></span>
<span id="cb211-3"><a href="multilevel-modelling-practical-3-week-4.html#cb211-3" tabindex="-1"></a>model1_int <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(data, <span class="fu">aes</span>(ses,mathach))<span class="sc">+</span></span>
<span id="cb211-4"><a href="multilevel-modelling-practical-3-week-4.html#cb211-4" tabindex="-1"></a>  <span class="fu">geom_line</span>(<span class="fu">aes</span>(<span class="at">y=</span>pred1,<span class="at">group=</span>school.f, </span>
<span id="cb211-5"><a href="multilevel-modelling-practical-3-week-4.html#cb211-5" tabindex="-1"></a>                <span class="at">col=</span>school.f))<span class="sc">+</span></span>
<span id="cb211-6"><a href="multilevel-modelling-practical-3-week-4.html#cb211-6" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="fu">aes</span>(ses,mathach, </span>
<span id="cb211-7"><a href="multilevel-modelling-practical-3-week-4.html#cb211-7" tabindex="-1"></a>                 <span class="at">col=</span>school.f), </span>
<span id="cb211-8"><a href="multilevel-modelling-practical-3-week-4.html#cb211-8" tabindex="-1"></a>             <span class="at">size =</span> <span class="fl">0.8</span>,</span>
<span id="cb211-9"><a href="multilevel-modelling-practical-3-week-4.html#cb211-9" tabindex="-1"></a>             <span class="at">alpha =</span> .<span class="dv">8</span>)<span class="sc">+</span> </span>
<span id="cb211-10"><a href="multilevel-modelling-practical-3-week-4.html#cb211-10" tabindex="-1"></a>  <span class="fu">geom_smooth</span>(<span class="at">method=</span><span class="st">&quot;lm&quot;</span>, </span>
<span id="cb211-11"><a href="multilevel-modelling-practical-3-week-4.html#cb211-11" tabindex="-1"></a>              <span class="at">se=</span><span class="cn">FALSE</span>, </span>
<span id="cb211-12"><a href="multilevel-modelling-practical-3-week-4.html#cb211-12" tabindex="-1"></a>              <span class="at">col=</span><span class="st">&quot;Red&quot;</span>)<span class="sc">+</span></span>
<span id="cb211-13"><a href="multilevel-modelling-practical-3-week-4.html#cb211-13" tabindex="-1"></a>  <span class="fu">ggtitle</span>(<span class="st">&quot;Multilevel model (Model1)&quot;</span>, </span>
<span id="cb211-14"><a href="multilevel-modelling-practical-3-week-4.html#cb211-14" tabindex="-1"></a>          <span class="at">subtitle=</span><span class="st">&quot;Random Intercept only&quot;</span>) <span class="sc">+</span></span>
<span id="cb211-15"><a href="multilevel-modelling-practical-3-week-4.html#cb211-15" tabindex="-1"></a>  <span class="fu">xlab</span>(<span class="st">&quot;Ses&quot;</span>) <span class="sc">+</span> </span>
<span id="cb211-16"><a href="multilevel-modelling-practical-3-week-4.html#cb211-16" tabindex="-1"></a>  <span class="fu">ylab</span>(<span class="st">&quot;Mathach&quot;</span>)<span class="sc">+</span></span>
<span id="cb211-17"><a href="multilevel-modelling-practical-3-week-4.html#cb211-17" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">legend.position =</span> <span class="st">&quot;none&quot;</span>)</span>
<span id="cb211-18"><a href="multilevel-modelling-practical-3-week-4.html#cb211-18" tabindex="-1"></a>model1_int</span></code></pre></div>
<p><img src="MLM_worksheets_files/figure-html/unnamed-chunk-78-1.png" width="672" /></p>
<p>The results of the above regression illustrate the importance of accounting for a multilevel structure. It is evident that had we used a simple linear regression (red line), we would have inadvertently overestimated the mean effect of <code>ses</code>. This is also easy to see by inspecting the model summary of the linear model, where <code>ses</code> has a coefficient of 3.45 while in the multilevel specification a coefficient of 2.12 with a random intercept variance that is considerably greater than zero with a value of 6.33.</p>
<p><span class="math inline">\(~\)</span></p>
</div>
<div id="diagnostics" class="section level3 hasAnchor" number="3.3.3">
<h3><span class="header-section-number">3.3.3</span> Diagnostics<a href="multilevel-modelling-practical-3-week-4.html#diagnostics" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Now we visualise results and conduct some diagnostic checks, in order to check for the adequacy of modelling assumptions. ALthough we have not (up until now) considered diagnostics in the multilevel context, we proceed as in the linear regression case, by checking normality of residuals and additionally, normality of the random effects!</p>
<p>We start by plotting the residuals vs the fitted values.</p>
<div class="sourceCode" id="cb212"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb212-1"><a href="multilevel-modelling-practical-3-week-4.html#cb212-1" tabindex="-1"></a><span class="fu">plot</span>(model.rint)</span></code></pre></div>
<p><img src="MLM_worksheets_files/figure-html/unnamed-chunk-79-1.png" width="672" /></p>
<p>Ideally, we should see here just random noise, that is no pattern at all. This is reasonably fulfilled, however there is impression of a diagonal field-like shape spanning from the top left to the bottom right. This likely indicates that a predictor variable which would have explained this slope has been omitted.</p>
<p><span class="math inline">\(~\)</span></p>
<p>Continue with inspection of model assumptions by looking at quantile-quantile plots for the residuals and random effects:</p>
<div class="sourceCode" id="cb213"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb213-1"><a href="multilevel-modelling-practical-3-week-4.html#cb213-1" tabindex="-1"></a><span class="fu">qqnorm</span>(<span class="fu">resid</span>(model.rint))</span>
<span id="cb213-2"><a href="multilevel-modelling-practical-3-week-4.html#cb213-2" tabindex="-1"></a><span class="fu">qqline</span>(<span class="fu">resid</span>(model.rint), </span>
<span id="cb213-3"><a href="multilevel-modelling-practical-3-week-4.html#cb213-3" tabindex="-1"></a>       <span class="at">col =</span> <span class="st">&quot;red&quot;</span>) </span></code></pre></div>
<p><img src="MLM_worksheets_files/figure-html/unnamed-chunk-80-1.png" width="672" /></p>
<div class="sourceCode" id="cb214"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb214-1"><a href="multilevel-modelling-practical-3-week-4.html#cb214-1" tabindex="-1"></a><span class="fu">qqnorm</span>(<span class="fu">ranef</span>(model.rint)<span class="sc">$</span>school.f[,<span class="dv">1</span>]) <span class="co"># check random effects</span></span>
<span id="cb214-2"><a href="multilevel-modelling-practical-3-week-4.html#cb214-2" tabindex="-1"></a><span class="fu">qqline</span>(<span class="fu">ranef</span>(model.rint)<span class="sc">$</span>school.f[,<span class="dv">1</span>], </span>
<span id="cb214-3"><a href="multilevel-modelling-practical-3-week-4.html#cb214-3" tabindex="-1"></a>       <span class="at">col =</span> <span class="st">&quot;red&quot;</span>)</span></code></pre></div>
<p><img src="MLM_worksheets_files/figure-html/unnamed-chunk-80-2.png" width="672" /></p>
<p>The QQ plots also look fairly acceptable (close to y=x line), indicating that the assumption of normality of the error terms and of the random effects is reasonably fulfilled.</p>
<p><span class="math inline">\(~\)</span></p>
</div>
<div id="include-a-second-fixed-effect-variable-gender" class="section level3 hasAnchor" number="3.3.4">
<h3><span class="header-section-number">3.3.4</span> Include a second fixed effect variable: gender<a href="multilevel-modelling-practical-3-week-4.html#include-a-second-fixed-effect-variable-gender" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>We will now perform multilevel modelling using random intercepts, this time including the dummy variable for female:</p>
<div class="sourceCode" id="cb215"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb215-1"><a href="multilevel-modelling-practical-3-week-4.html#cb215-1" tabindex="-1"></a>model2.rint <span class="ot">&lt;-</span> <span class="fu">lmer</span>(mathach <span class="sc">~</span> ses <span class="sc">+</span> female <span class="sc">+</span> (<span class="dv">1</span> <span class="sc">|</span> school.f), <span class="at">data=</span>data)</span>
<span id="cb215-2"><a href="multilevel-modelling-practical-3-week-4.html#cb215-2" tabindex="-1"></a><span class="co">#summary(model2.rint) #uncomment if you&#39;d like to interogate the model output</span></span></code></pre></div>
<p><span class="math inline">\(~\)</span></p>
<p>We will plot the fitted values, categorised by gender. We want two plots, side-by-side, showing the fitted lines for each school.</p>
<div class="sourceCode" id="cb216"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb216-1"><a href="multilevel-modelling-practical-3-week-4.html#cb216-1" tabindex="-1"></a>data<span class="sc">$</span>pred2 <span class="ot">&lt;-</span> <span class="fu">predict</span>(model2.rint)</span>
<span id="cb216-2"><a href="multilevel-modelling-practical-3-week-4.html#cb216-2" tabindex="-1"></a></span>
<span id="cb216-3"><a href="multilevel-modelling-practical-3-week-4.html#cb216-3" tabindex="-1"></a>gender_names <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">&quot;0&quot;</span> <span class="ot">=</span><span class="st">&quot;Male&quot;</span>,<span class="st">&quot;1&quot;</span><span class="ot">=</span><span class="st">&quot;Female&quot;</span>) <span class="co">#define labels for facet_grid</span></span>
<span id="cb216-4"><a href="multilevel-modelling-practical-3-week-4.html#cb216-4" tabindex="-1"></a></span>
<span id="cb216-5"><a href="multilevel-modelling-practical-3-week-4.html#cb216-5" tabindex="-1"></a>model2_int <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(data,<span class="fu">aes</span>(ses,mathach))<span class="sc">+</span></span>
<span id="cb216-6"><a href="multilevel-modelling-practical-3-week-4.html#cb216-6" tabindex="-1"></a>  <span class="fu">geom_line</span>(<span class="fu">aes</span>(<span class="at">y=</span>pred2,<span class="at">group=</span>school.f, <span class="at">col=</span>school.f))<span class="sc">+</span></span>
<span id="cb216-7"><a href="multilevel-modelling-practical-3-week-4.html#cb216-7" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="fu">aes</span>(ses,mathach, <span class="at">col=</span>school.f),</span>
<span id="cb216-8"><a href="multilevel-modelling-practical-3-week-4.html#cb216-8" tabindex="-1"></a>             <span class="at">size =</span> <span class="fl">0.8</span>,</span>
<span id="cb216-9"><a href="multilevel-modelling-practical-3-week-4.html#cb216-9" tabindex="-1"></a>             <span class="at">alpha =</span> .<span class="dv">8</span>)<span class="sc">+</span> </span>
<span id="cb216-10"><a href="multilevel-modelling-practical-3-week-4.html#cb216-10" tabindex="-1"></a>  <span class="fu">geom_smooth</span>(<span class="at">method=</span><span class="st">&quot;lm&quot;</span>, </span>
<span id="cb216-11"><a href="multilevel-modelling-practical-3-week-4.html#cb216-11" tabindex="-1"></a>              <span class="at">se=</span><span class="cn">FALSE</span>, <span class="at">col=</span><span class="st">&quot;Red&quot;</span>)<span class="sc">+</span></span>
<span id="cb216-12"><a href="multilevel-modelling-practical-3-week-4.html#cb216-12" tabindex="-1"></a>   <span class="fu">ggtitle</span>(<span class="st">&quot;Multilevel model (Model2)&quot;</span>, </span>
<span id="cb216-13"><a href="multilevel-modelling-practical-3-week-4.html#cb216-13" tabindex="-1"></a>           <span class="at">subtitle=</span><span class="st">&quot;By Gender&quot;</span>) <span class="sc">+</span></span>
<span id="cb216-14"><a href="multilevel-modelling-practical-3-week-4.html#cb216-14" tabindex="-1"></a>  <span class="fu">facet_grid</span>(<span class="sc">~</span>female, </span>
<span id="cb216-15"><a href="multilevel-modelling-practical-3-week-4.html#cb216-15" tabindex="-1"></a>             <span class="at">labeller =</span> <span class="fu">as_labeller</span>(gender_names))<span class="sc">+</span></span>
<span id="cb216-16"><a href="multilevel-modelling-practical-3-week-4.html#cb216-16" tabindex="-1"></a>  <span class="fu">xlab</span>(<span class="st">&quot;Ses&quot;</span>) <span class="sc">+</span> </span>
<span id="cb216-17"><a href="multilevel-modelling-practical-3-week-4.html#cb216-17" tabindex="-1"></a>  <span class="fu">ylab</span>(<span class="st">&quot;Mathach&quot;</span>)<span class="sc">+</span></span>
<span id="cb216-18"><a href="multilevel-modelling-practical-3-week-4.html#cb216-18" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">legend.position =</span> <span class="st">&quot;none&quot;</span>)</span>
<span id="cb216-19"><a href="multilevel-modelling-practical-3-week-4.html#cb216-19" tabindex="-1"></a>model2_int</span></code></pre></div>
<p><img src="MLM_worksheets_files/figure-html/unnamed-chunk-82-1.png" width="672" />
There is a lot going on here! Try to understand each line, and what is being plotted. Consider writing out the mathematical form of the model, or discuss with each other / the instructor as to what this form takes.</p>
<p>** End of lab!</p>

</div>
</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="multilevel-modelling-practical-2-week-3.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="multilevel-modelling-practical-4-week-5.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": false,
"twitter": false,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"whatsapp": false,
"all": false
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": null,
"text": null
},
"history": {
"link": null,
"text": null
},
"view": {
"link": null,
"text": null
},
"download": null,
"search": {
"engine": "fuse",
"options": null
},
"toc": {
"collapse": "section",
"scroll_highlight": true,
"search": true,
"sidebar": true
}
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.9/latest.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
