<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>8 Multilevel Modelling Practical 8 (Week 9) | MLM_worksheets.knit</title>
  <meta name="description" content="" />
  <meta name="generator" content="bookdown 0.42 and GitBook 2.6.7" />

  <meta property="og:title" content="8 Multilevel Modelling Practical 8 (Week 9) | MLM_worksheets.knit" />
  <meta property="og:type" content="book" />
  
  
  

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="8 Multilevel Modelling Practical 8 (Week 9) | MLM_worksheets.knit" />
  
  
  

<meta name="author" content="Daniele Turchetti" />



  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="multilevel-modelling-practical-7-week-8.html"/>
<link rel="next" href="multilevel-modelling-practical-9-week-10.html"/>
<script src="libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/fuse.js@6.4.6/dist/fuse.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />








<link href="libs/anchor-sections-1.1.0/anchor-sections.css" rel="stylesheet" />
<link href="libs/anchor-sections-1.1.0/anchor-sections-hash.css" rel="stylesheet" />
<script src="libs/anchor-sections-1.1.0/anchor-sections.js"></script>


<style type="text/css">
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { display: inline-block; text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { color: #008000; } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { color: #008000; font-weight: bold; } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

<style type="text/css">
  
  div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
</style>

<link rel="stylesheet" href="styles.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">Home</a></li>

<li class="divider"></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i>Welcome to multilevel modelling</a></li>
<li class="chapter" data-level="1" data-path="multilevel-modelling-practical-1-week-2.html"><a href="multilevel-modelling-practical-1-week-2.html"><i class="fa fa-check"></i><b>1</b> Multilevel Modelling Practical 1 (Week 2)</a>
<ul>
<li class="chapter" data-level="1.1" data-path="multilevel-modelling-practical-1-week-2.html"><a href="multilevel-modelling-practical-1-week-2.html#instructions-start-here"><i class="fa fa-check"></i><b>1.1</b> Instructions – start here!</a></li>
<li class="chapter" data-level="1.2" data-path="multilevel-modelling-practical-1-week-2.html"><a href="multilevel-modelling-practical-1-week-2.html#exercises-1"><i class="fa fa-check"></i><b>1.2</b> Exercises 1</a></li>
<li class="chapter" data-level="1.3" data-path="multilevel-modelling-practical-1-week-2.html"><a href="multilevel-modelling-practical-1-week-2.html#exercises-2"><i class="fa fa-check"></i><b>1.3</b> Exercises 2</a></li>
</ul></li>
<li class="chapter" data-level="2" data-path="multilevel-modelling-practical-2-week-3.html"><a href="multilevel-modelling-practical-2-week-3.html"><i class="fa fa-check"></i><b>2</b> Multilevel Modelling Practical 2 (Week 3)</a>
<ul>
<li class="chapter" data-level="2.1" data-path="multilevel-modelling-practical-2-week-3.html"><a href="multilevel-modelling-practical-2-week-3.html#instructions-start-here-1"><i class="fa fa-check"></i><b>2.1</b> Instructions – start here!</a></li>
<li class="chapter" data-level="2.2" data-path="multilevel-modelling-practical-2-week-3.html"><a href="multilevel-modelling-practical-2-week-3.html#exercises-1-1"><i class="fa fa-check"></i><b>2.2</b> Exercises 1</a>
<ul>
<li class="chapter" data-level="2.2.1" data-path="multilevel-modelling-practical-2-week-3.html"><a href="multilevel-modelling-practical-2-week-3.html#acquire-and-prepare-data"><i class="fa fa-check"></i><b>2.2.1</b> Acquire and prepare data</a></li>
<li class="chapter" data-level="2.2.2" data-path="multilevel-modelling-practical-2-week-3.html"><a href="multilevel-modelling-practical-2-week-3.html#exploratory-analysis"><i class="fa fa-check"></i><b>2.2.2</b> Exploratory analysis</a></li>
<li class="chapter" data-level="2.2.3" data-path="multilevel-modelling-practical-2-week-3.html"><a href="multilevel-modelling-practical-2-week-3.html#naive-simple-linear-regression-models"><i class="fa fa-check"></i><b>2.2.3</b> Naive simple linear regression models</a></li>
</ul></li>
<li class="chapter" data-level="2.3" data-path="multilevel-modelling-practical-2-week-3.html"><a href="multilevel-modelling-practical-2-week-3.html#exercise-2"><i class="fa fa-check"></i><b>2.3</b> Exercise 2</a></li>
<li class="chapter" data-level="2.4" data-path="multilevel-modelling-practical-2-week-3.html"><a href="multilevel-modelling-practical-2-week-3.html#exercise-3-if-time"><i class="fa fa-check"></i><b>2.4</b> Exercise 3 (if time)</a></li>
</ul></li>
<li class="chapter" data-level="3" data-path="multilevel-modelling-practical-3-week-4.html"><a href="multilevel-modelling-practical-3-week-4.html"><i class="fa fa-check"></i><b>3</b> Multilevel Modelling Practical 3 (Week 4)</a>
<ul>
<li class="chapter" data-level="3.1" data-path="multilevel-modelling-practical-3-week-4.html"><a href="multilevel-modelling-practical-3-week-4.html#instructions-start-here-2"><i class="fa fa-check"></i><b>3.1</b> Instructions – start here!</a></li>
<li class="chapter" data-level="3.2" data-path="multilevel-modelling-practical-3-week-4.html"><a href="multilevel-modelling-practical-3-week-4.html#exercise-1"><i class="fa fa-check"></i><b>3.2</b> Exercise 1</a>
<ul>
<li class="chapter" data-level="3.2.1" data-path="multilevel-modelling-practical-3-week-4.html"><a href="multilevel-modelling-practical-3-week-4.html#preparation-of-the-data-set"><i class="fa fa-check"></i><b>3.2.1</b> Preparation of the data set</a></li>
<li class="chapter" data-level="3.2.2" data-path="multilevel-modelling-practical-3-week-4.html"><a href="multilevel-modelling-practical-3-week-4.html#fitting-the-random-intercept-and-slope-model"><i class="fa fa-check"></i><b>3.2.2</b> Fitting the random intercept and slope model</a></li>
<li class="chapter" data-level="3.2.3" data-path="multilevel-modelling-practical-3-week-4.html"><a href="multilevel-modelling-practical-3-week-4.html#fitted-lines-by-class"><i class="fa fa-check"></i><b>3.2.3</b> Fitted lines by class</a></li>
<li class="chapter" data-level="3.2.4" data-path="multilevel-modelling-practical-3-week-4.html"><a href="multilevel-modelling-practical-3-week-4.html#the-intercept-only-empty-model-and-icc"><i class="fa fa-check"></i><b>3.2.4</b> The intercept-only / empty model and ICC</a></li>
<li class="chapter" data-level="3.2.5" data-path="multilevel-modelling-practical-3-week-4.html"><a href="multilevel-modelling-practical-3-week-4.html#the-random-intercept-model-with-covariate"><i class="fa fa-check"></i><b>3.2.5</b> The random intercept model (with covariate)</a></li>
</ul></li>
<li class="chapter" data-level="3.3" data-path="multilevel-modelling-practical-3-week-4.html"><a href="multilevel-modelling-practical-3-week-4.html#exercise-2-1"><i class="fa fa-check"></i><b>3.3</b> Exercise 2</a>
<ul>
<li class="chapter" data-level="3.3.1" data-path="multilevel-modelling-practical-3-week-4.html"><a href="multilevel-modelling-practical-3-week-4.html#preparation"><i class="fa fa-check"></i><b>3.3.1</b> Preparation</a></li>
<li class="chapter" data-level="3.3.2" data-path="multilevel-modelling-practical-3-week-4.html"><a href="multilevel-modelling-practical-3-week-4.html#the-random-intercept-model"><i class="fa fa-check"></i><b>3.3.2</b> The random intercept model</a></li>
<li class="chapter" data-level="3.3.3" data-path="multilevel-modelling-practical-3-week-4.html"><a href="multilevel-modelling-practical-3-week-4.html#diagnostics"><i class="fa fa-check"></i><b>3.3.3</b> Diagnostics</a></li>
<li class="chapter" data-level="3.3.4" data-path="multilevel-modelling-practical-3-week-4.html"><a href="multilevel-modelling-practical-3-week-4.html#include-a-second-fixed-effect-variable-gender"><i class="fa fa-check"></i><b>3.3.4</b> Include a second fixed effect variable: gender</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="4" data-path="multilevel-modelling-practical-4-week-5.html"><a href="multilevel-modelling-practical-4-week-5.html"><i class="fa fa-check"></i><b>4</b> Multilevel Modelling Practical 4 (Week 5)</a>
<ul>
<li class="chapter" data-level="4.1" data-path="multilevel-modelling-practical-4-week-5.html"><a href="multilevel-modelling-practical-4-week-5.html#instructions-start-here-3"><i class="fa fa-check"></i><b>4.1</b> Instructions – start here!</a></li>
<li class="chapter" data-level="4.2" data-path="multilevel-modelling-practical-4-week-5.html"><a href="multilevel-modelling-practical-4-week-5.html#exercise-1-analysis-of-the-active-time-study-data-lecture-5"><i class="fa fa-check"></i><b>4.2</b> Exercise 1: Analysis of the Active Time study data (lecture 5)</a>
<ul>
<li class="chapter" data-level="4.2.1" data-path="multilevel-modelling-practical-4-week-5.html"><a href="multilevel-modelling-practical-4-week-5.html#how-important-is-group-structure-vpcs-and-iccs"><i class="fa fa-check"></i><b>4.2.1</b> How important is group structure? (VPCs and ICCs)</a></li>
<li class="chapter" data-level="4.2.2" data-path="multilevel-modelling-practical-4-week-5.html"><a href="multilevel-modelling-practical-4-week-5.html#three-level-model-with-explanatory-variables"><i class="fa fa-check"></i><b>4.2.2</b> Three level Model with explanatory variables</a></li>
<li class="chapter" data-level="4.2.3" data-path="multilevel-modelling-practical-4-week-5.html"><a href="multilevel-modelling-practical-4-week-5.html#comparison-of-empty-model-with-model-with-explanatory-variables"><i class="fa fa-check"></i><b>4.2.3</b> Comparison of empty model with model with explanatory variables</a></li>
<li class="chapter" data-level="4.2.4" data-path="multilevel-modelling-practical-4-week-5.html"><a href="multilevel-modelling-practical-4-week-5.html#further-analysis-bottom-up-approach"><i class="fa fa-check"></i><b>4.2.4</b> Further analysis (bottom up approach)</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="5" data-path="multilevel-modelling-practical-5-week-6.html"><a href="multilevel-modelling-practical-5-week-6.html"><i class="fa fa-check"></i><b>5</b> Multilevel Modelling Practical 5 (Week 6)</a>
<ul>
<li class="chapter" data-level="5.1" data-path="multilevel-modelling-practical-5-week-6.html"><a href="multilevel-modelling-practical-5-week-6.html#instructions---start-here"><i class="fa fa-check"></i><b>5.1</b> Instructions - start here!</a>
<ul>
<li class="chapter" data-level="5.1.1" data-path="multilevel-modelling-practical-5-week-6.html"><a href="multilevel-modelling-practical-5-week-6.html#overview"><i class="fa fa-check"></i><b>5.1.1</b> Overview</a></li>
<li class="chapter" data-level="5.1.2" data-path="multilevel-modelling-practical-5-week-6.html"><a href="multilevel-modelling-practical-5-week-6.html#multilevel-modelling-with-longitudinal-data"><i class="fa fa-check"></i><b>5.1.2</b> Multilevel modelling with longitudinal data</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="6" data-path="multilevel-modelling-practical-6-week-7.html"><a href="multilevel-modelling-practical-6-week-7.html"><i class="fa fa-check"></i><b>6</b> Multilevel Modelling Practical 6 (Week 7)</a>
<ul>
<li class="chapter" data-level="6.1" data-path="multilevel-modelling-practical-6-week-7.html"><a href="multilevel-modelling-practical-6-week-7.html#instructions---start-here-1"><i class="fa fa-check"></i><b>6.1</b> Instructions - start here!</a></li>
<li class="chapter" data-level="6.2" data-path="multilevel-modelling-practical-6-week-7.html"><a href="multilevel-modelling-practical-6-week-7.html#exercise-1-long-and-wide-data-shape"><i class="fa fa-check"></i><b>6.2</b> Exercise 1 (Long and wide data shape)</a>
<ul>
<li class="chapter" data-level="6.2.1" data-path="multilevel-modelling-practical-6-week-7.html"><a href="multilevel-modelling-practical-6-week-7.html#regression-vs-multilevel-analysis"><i class="fa fa-check"></i><b>6.2.1</b> Regression vs multilevel analysis</a></li>
</ul></li>
<li class="chapter" data-level="6.3" data-path="multilevel-modelling-practical-6-week-7.html"><a href="multilevel-modelling-practical-6-week-7.html#exercise-2-simulation-from-the-two-level-longitudinal-model"><i class="fa fa-check"></i><b>6.3</b> Exercise 2 (simulation from the two-level longitudinal model)</a></li>
<li class="chapter" data-level="6.4" data-path="multilevel-modelling-practical-6-week-7.html"><a href="multilevel-modelling-practical-6-week-7.html#end-of-lab"><i class="fa fa-check"></i><b>6.4</b> End of lab!</a></li>
</ul></li>
<li class="chapter" data-level="7" data-path="multilevel-modelling-practical-7-week-8.html"><a href="multilevel-modelling-practical-7-week-8.html"><i class="fa fa-check"></i><b>7</b> Multilevel Modelling Practical 7 (Week 8)</a>
<ul>
<li class="chapter" data-level="7.1" data-path="multilevel-modelling-practical-7-week-8.html"><a href="multilevel-modelling-practical-7-week-8.html#instructions---start-here-2"><i class="fa fa-check"></i><b>7.1</b> Instructions - start here!</a></li>
<li class="chapter" data-level="7.2" data-path="multilevel-modelling-practical-7-week-8.html"><a href="multilevel-modelling-practical-7-week-8.html#exercise-1-aids-data-example-2-from-lecture-7"><i class="fa fa-check"></i><b>7.2</b> Exercise 1 (Aids data: Example 2 from lecture 7)</a></li>
<li class="chapter" data-level="7.3" data-path="multilevel-modelling-practical-7-week-8.html"><a href="multilevel-modelling-practical-7-week-8.html#exercise-2-leukaemia-data-example-3-from-lecture-7"><i class="fa fa-check"></i><b>7.3</b> Exercise 2 (Leukaemia data: Example 3 from lecture 7)</a></li>
<li class="chapter" data-level="7.4" data-path="multilevel-modelling-practical-7-week-8.html"><a href="multilevel-modelling-practical-7-week-8.html#exercise-3-toxoplasmosis-data-binomial-logistic-regression"><i class="fa fa-check"></i><b>7.4</b> Exercise 3: Toxoplasmosis data (Binomial logistic regression)</a></li>
<li class="chapter" data-level="7.5" data-path="multilevel-modelling-practical-7-week-8.html"><a href="multilevel-modelling-practical-7-week-8.html#end-of-lab-1"><i class="fa fa-check"></i><b>7.5</b> ## End of lab!</a></li>
</ul></li>
<li class="chapter" data-level="8" data-path="multilevel-modelling-practical-8-week-9.html"><a href="multilevel-modelling-practical-8-week-9.html"><i class="fa fa-check"></i><b>8</b> Multilevel Modelling Practical 8 (Week 9)</a>
<ul>
<li class="chapter" data-level="8.1" data-path="multilevel-modelling-practical-8-week-9.html"><a href="multilevel-modelling-practical-8-week-9.html#instructions---start-here-3"><i class="fa fa-check"></i><b>8.1</b> Instructions - start here!</a></li>
<li class="chapter" data-level="8.2" data-path="multilevel-modelling-practical-8-week-9.html"><a href="multilevel-modelling-practical-8-week-9.html#preliminaries"><i class="fa fa-check"></i><b>8.2</b> Preliminaries</a></li>
<li class="chapter" data-level="8.3" data-path="multilevel-modelling-practical-8-week-9.html"><a href="multilevel-modelling-practical-8-week-9.html#exercise-1-betablocker-data"><i class="fa fa-check"></i><b>8.3</b> Exercise 1: Betablocker data</a></li>
<li class="chapter" data-level="8.4" data-path="multilevel-modelling-practical-8-week-9.html"><a href="multilevel-modelling-practical-8-week-9.html#exercise-2-digging-deeper"><i class="fa fa-check"></i><b>8.4</b> Exercise 2 (digging deeper)</a></li>
<li class="chapter" data-level="8.5" data-path="multilevel-modelling-practical-8-week-9.html"><a href="multilevel-modelling-practical-8-week-9.html#exercise-3-optional-toxoplasmosis-data-revisited"><i class="fa fa-check"></i><b>8.5</b> Exercise 3 (optional): Toxoplasmosis data revisited</a></li>
<li class="chapter" data-level="8.6" data-path="multilevel-modelling-practical-8-week-9.html"><a href="multilevel-modelling-practical-8-week-9.html#summative-assessment"><i class="fa fa-check"></i><b>8.6</b> Summative assessment</a></li>
<li class="chapter" data-level="8.7" data-path="multilevel-modelling-practical-8-week-9.html"><a href="multilevel-modelling-practical-8-week-9.html#end-of-lab-2"><i class="fa fa-check"></i><b>8.7</b> ## End of lab!</a></li>
</ul></li>
<li class="chapter" data-level="9" data-path="multilevel-modelling-practical-9-week-10.html"><a href="multilevel-modelling-practical-9-week-10.html"><i class="fa fa-check"></i><b>9</b> Multilevel Modelling Practical 9 (Week 10)</a>
<ul>
<li class="chapter" data-level="9.1" data-path="multilevel-modelling-practical-9-week-10.html"><a href="multilevel-modelling-practical-9-week-10.html#dealing-with-missing-values"><i class="fa fa-check"></i><b>9.1</b> Dealing with missing values</a></li>
</ul></li>
</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./"></a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="multilevel-modelling-practical-8-week-9" class="section level1 hasAnchor" number="8">
<h1><span class="header-section-number">8</span> Multilevel Modelling Practical 8 (Week 9)<a href="multilevel-modelling-practical-8-week-9.html#multilevel-modelling-practical-8-week-9" class="anchor-section" aria-label="Anchor link to header"></a></h1>
<div id="instructions---start-here-3" class="section level2 hasAnchor" number="8.1">
<h2><span class="header-section-number">8.1</span> Instructions - start here!<a href="multilevel-modelling-practical-8-week-9.html#instructions---start-here-3" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p><strong>Exercise 1</strong> involves the analysis of the Betablocker data set used in last week’s lecture. <strong>Exercise 2</strong> digs a little deeper using the same data set. <strong>Exercise 3</strong> considers the Toxoplasmosis data from last week’s lab. The remaining time can be used to work on the summative assessment.</p>
</div>
<div id="preliminaries" class="section level2 hasAnchor" number="8.2">
<h2><span class="header-section-number">8.2</span> Preliminaries<a href="multilevel-modelling-practical-8-week-9.html#preliminaries" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>We load the R packages <em>lme4</em> and <em>ggplot2</em>.</p>
<div class="sourceCode" id="cb368"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb368-1"><a href="multilevel-modelling-practical-8-week-9.html#cb368-1" tabindex="-1"></a><span class="fu">require</span>(lme4)       <span class="co"># contains glmer</span></span>
<span id="cb368-2"><a href="multilevel-modelling-practical-8-week-9.html#cb368-2" tabindex="-1"></a><span class="fu">require</span>(ggplot2)    <span class="co"># for the use of ggplot</span></span></code></pre></div>
</div>
<div id="exercise-1-betablocker-data" class="section level2 hasAnchor" number="8.3">
<h2><span class="header-section-number">8.3</span> Exercise 1: Betablocker data<a href="multilevel-modelling-practical-8-week-9.html#exercise-1-betablocker-data" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>We will initially reproduce the analysis as demonstrated in the lecture. We read the betablocker data directly from the internet.</p>
<div class="sourceCode" id="cb369"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb369-1"><a href="multilevel-modelling-practical-8-week-9.html#cb369-1" tabindex="-1"></a>betablok <span class="ot">&lt;-</span> <span class="fu">read.table</span>(</span>
<span id="cb369-2"><a href="multilevel-modelling-practical-8-week-9.html#cb369-2" tabindex="-1"></a>  <span class="st">&#39;https://andygolightly.github.io/teaching/MATH43515/betablok.dat&#39;</span>)</span>
<span id="cb369-3"><a href="multilevel-modelling-practical-8-week-9.html#cb369-3" tabindex="-1"></a><span class="fu">head</span>(betablok)</span></code></pre></div>
<pre><code>##   V1  V2
## 1  3  39
## 2  3  38
## 3 14 116
## 4  7 114
## 5 11  93
## 6  5  69</code></pre>
<p>Add trial and centre information:</p>
<div class="sourceCode" id="cb371"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb371-1"><a href="multilevel-modelling-practical-8-week-9.html#cb371-1" tabindex="-1"></a><span class="fu">names</span>(betablok) <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">&#39;r&#39;</span>,<span class="st">&#39;n&#39;</span>)</span>
<span id="cb371-2"><a href="multilevel-modelling-practical-8-week-9.html#cb371-2" tabindex="-1"></a>betablok<span class="sc">$</span>treat <span class="ot">&lt;-</span> <span class="fu">factor</span>(<span class="fu">gl</span>(<span class="dv">2</span>,<span class="dv">1</span>),<span class="at">labels=</span><span class="fu">c</span>(<span class="dv">0</span>,<span class="dv">1</span>))</span>
<span id="cb371-3"><a href="multilevel-modelling-practical-8-week-9.html#cb371-3" tabindex="-1"></a>betablok<span class="sc">$</span>center <span class="ot">&lt;-</span> <span class="fu">gl</span>(<span class="dv">22</span>,<span class="dv">2</span>)</span></code></pre></div>
<p>Let’s take a quick look at data layout:</p>
<div class="sourceCode" id="cb372"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb372-1"><a href="multilevel-modelling-practical-8-week-9.html#cb372-1" tabindex="-1"></a><span class="fu">dim</span>(betablok)</span></code></pre></div>
<pre><code>## [1] 44  4</code></pre>
<div class="sourceCode" id="cb374"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb374-1"><a href="multilevel-modelling-practical-8-week-9.html#cb374-1" tabindex="-1"></a><span class="fu">head</span>(betablok)</span></code></pre></div>
<pre><code>##    r   n treat center
## 1  3  39     0      1
## 2  3  38     1      1
## 3 14 116     0      2
## 4  7 114     1      2
## 5 11  93     0      3
## 6  5  69     1      3</code></pre>
<p>We now consider the GLM fit after ignoring multi-level structure:</p>
<div class="sourceCode" id="cb376"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb376-1"><a href="multilevel-modelling-practical-8-week-9.html#cb376-1" tabindex="-1"></a>betablok.glm <span class="ot">&lt;-</span> <span class="fu">glm</span>(<span class="fu">cbind</span>(r,(n<span class="sc">-</span>r))<span class="sc">~</span>treat,<span class="at">data=</span>betablok,<span class="at">family=</span>binomial)</span>
<span id="cb376-2"><a href="multilevel-modelling-practical-8-week-9.html#cb376-2" tabindex="-1"></a><span class="fu">summary</span>(betablok.glm)</span></code></pre></div>
<pre><code>## 
## Call:
## glm(formula = cbind(r, (n - r)) ~ treat, family = binomial, data = betablok)
## 
## Coefficients:
##             Estimate Std. Error z value Pr(&gt;|z|)    
## (Intercept) -2.19711    0.03359 -65.417  &lt; 2e-16 ***
## treat1      -0.25737    0.04942  -5.207 1.91e-07 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## (Dispersion parameter for binomial family taken to be 1)
## 
##     Null deviance: 332.99  on 43  degrees of freedom
## Residual deviance: 305.76  on 42  degrees of freedom
## AIC: 527.19
## 
## Number of Fisher Scoring iterations: 4</code></pre>
<p>Note the AIC value of 527. Recall that AIC is given by <span class="math inline">\(2(p+1)-2\log\hat{L}\)</span> where <span class="math inline">\(\log\hat{L}\)</span> is the maximised log-likelihood. When comparing two (potentially non-nested) models, we prefer the model with smaller AIC.</p>
<p><span class="math inline">\(~\)</span></p>
<p>Now account for two-level structure, with <code>center</code> (i.e. hospital) in the upper level:</p>
<div class="sourceCode" id="cb378"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb378-1"><a href="multilevel-modelling-practical-8-week-9.html#cb378-1" tabindex="-1"></a><span class="fu">summary</span>(betablok.glmer <span class="ot">&lt;-</span> <span class="fu">glmer</span>(<span class="fu">cbind</span>(r,(n<span class="sc">-</span>r))<span class="sc">~</span>treat<span class="sc">+</span>(<span class="dv">1</span><span class="sc">|</span>center), <span class="at">data=</span>betablok, <span class="at">family=</span>binomial)) </span></code></pre></div>
<pre><code>## Generalized linear mixed model fit by maximum likelihood (Laplace Approximation) [&#39;glmerMod&#39;]
##  Family: binomial  ( logit )
## Formula: cbind(r, (n - r)) ~ treat + (1 | center)
##    Data: betablok
## 
##      AIC      BIC   logLik deviance df.resid 
##    324.4    329.8   -159.2    318.4       41 
## 
## Scaled residuals: 
##     Min      1Q  Median      3Q     Max 
## -1.8876 -0.5129  0.0605  0.4969  1.8623 
## 
## Random effects:
##  Groups Name        Variance Std.Dev.
##  center (Intercept) 0.2362   0.486   
## Number of obs: 44, groups:  center, 22
## 
## Fixed effects:
##             Estimate Std. Error z value Pr(&gt;|z|)    
## (Intercept) -2.19618    0.11292 -19.450  &lt; 2e-16 ***
## treat1      -0.26091    0.04982  -5.237 1.63e-07 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Correlation of Fixed Effects:
##        (Intr)
## treat1 -0.205</code></pre>
<p>Note the AIC value of 324. Let’s think about the treatment effect. We have the following model:
<span class="math display">\[
Y_{ij} \sim \text{Binomial}(n_{ij},\pi_{ij})
\]</span>
for treatment <span class="math inline">\(i\)</span> in center <span class="math inline">\(j\)</span>. Note that <span class="math inline">\(\pi_{ij}\)</span> is the probability of patient mortality for that treatment-center combination. We further have via the <em>logit</em> link that
<span class="math display">\[
\log\left(\frac{\pi_{ij}}{1-\pi_{ij}}\right)=a+u_j+b x_{ij}
\]</span>
which gives
<span class="math display">\[
\pi_{ij}= \frac{e^{a+u_j+b x_{ij}}}{1+e^{a+u_j+b x_{ij}}}
\]</span>
where <span class="math inline">\(x_{ij}\)</span> is 0 or 1 for no treatment versus treatment and <span class="math inline">\(u_j\sim N(0,\sigma^2_u)\)</span> is the random intercept term. When <span class="math inline">\(x_{ij}=0\)</span> the expected log-odds ratio is
<span class="math display">\[
\hat{a}=-2.2.
\]</span>
When <span class="math inline">\(x_{ij}=1\)</span>, the expected log-odds ratio is
<span class="math display">\[
\hat{a}+\hat{b} = -2.2 - 0.26.
\]</span>
Hence, the effect of treatment is the change the log-odds ratio by -0.26 and therefore multiplys the odds-ratio (in favour of death) by <span class="math inline">\(\exp(-0.26)=0.77\)</span>. That is, the treatment <em>appears to be effective in reducing probability of patient mortality</em>.</p>
<p>This observation has also been made in the literature; e.g. Aitkin et al (2009, Statistical Modelling in R, page 526), note: “The treatment produces a significant, though small, reduction in death risk compared to the control: the odds of death are reduced…”.</p>
<p><span class="math inline">\(~\)</span></p>
<p>We can do a little diagnostc checking by looking at the normality assumption for the random intercept terms:</p>
<div class="sourceCode" id="cb380"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb380-1"><a href="multilevel-modelling-practical-8-week-9.html#cb380-1" tabindex="-1"></a><span class="fu">qqnorm</span>(<span class="fu">ranef</span>(betablok.glmer)<span class="sc">$</span>center[,<span class="dv">1</span>])</span>
<span id="cb380-2"><a href="multilevel-modelling-practical-8-week-9.html#cb380-2" tabindex="-1"></a><span class="fu">qqline</span>(<span class="fu">ranef</span>(betablok.glmer)<span class="sc">$</span>center[,<span class="dv">1</span>])</span></code></pre></div>
<p><img src="MLM_worksheets_files/figure-html/unnamed-chunk-179-1.png" width="672" /></p>
<p>which doesn’t look too bad given the size of the data set.</p>
</div>
<div id="exercise-2-digging-deeper" class="section level2 hasAnchor" number="8.4">
<h2><span class="header-section-number">8.4</span> Exercise 2 (digging deeper)<a href="multilevel-modelling-practical-8-week-9.html#exercise-2-digging-deeper" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>This is a multi-centre trial, so (in terms of analysis) comparable to a multi-site trial. Hence, a natural extension of the preceding analysis would be the consideration of random slopes.</p>
<p>Adapt the model <code>betablok.glmer</code> accordingly so that it allows for centre-specific slopes.</p>
<div class="sourceCode" id="cb381"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb381-1"><a href="multilevel-modelling-practical-8-week-9.html#cb381-1" tabindex="-1"></a><span class="fu">summary</span>(betablok.glmer2<span class="ot">&lt;-</span><span class="fu">glmer</span>(<span class="fu">cbind</span>(r,(n<span class="sc">-</span>r))<span class="sc">~</span>treat<span class="sc">+</span>(treat<span class="sc">|</span>center),  </span>
<span id="cb381-2"><a href="multilevel-modelling-practical-8-week-9.html#cb381-2" tabindex="-1"></a>                               <span class="at">data=</span>betablok,<span class="at">family=</span>binomial)) </span></code></pre></div>
<pre><code>## Generalized linear mixed model fit by maximum likelihood (Laplace Approximation) [&#39;glmerMod&#39;]
##  Family: binomial  ( logit )
## Formula: cbind(r, (n - r)) ~ treat + (treat | center)
##    Data: betablok
## 
##      AIC      BIC   logLik deviance df.resid 
##    327.7    336.6   -158.8    317.7       39 
## 
## Scaled residuals: 
##      Min       1Q   Median       3Q      Max 
## -1.45612 -0.40887  0.02525  0.44137  1.39542 
## 
## Random effects:
##  Groups Name        Variance Std.Dev. Corr 
##  center (Intercept) 0.254613 0.5046        
##         treat1      0.009585 0.0979   -0.45
## Number of obs: 44, groups:  center, 22
## 
## Fixed effects:
##             Estimate Std. Error z value Pr(&gt;|z|)    
## (Intercept) -2.20413    0.11749 -18.760  &lt; 2e-16 ***
## treat1      -0.24681    0.05888  -4.192 2.77e-05 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Correlation of Fixed Effects:
##        (Intr)
## treat1 -0.364</code></pre>
<p><strong>TASK:</strong> Consider AIC. Do the random slopes appear to be worth including?</p>
<details>
<summary>
Click for solution
</summary>
The AIC is 327.7, which has increased (from 324.4 for the random intercept model). Hence, it appears that random slopes are not needed.
</details>
<p><span class="math inline">\(~\)</span></p>
<p><strong>TASK:</strong> Apply the <code>anova</code> function on the pair of models to endorse your judgement. (Note: both models are fitted using maximum likelihood so using <code>anova</code> here is perfectly acceptible. We used <code>ranova</code> to compare models with and without random slopes in the linear mixed effect model setting due to <code>lmer</code> using restricted maximum likelihood to perform the fitting.)</p>
<details>
<summary>
Click for solution
</summary>
<div class="sourceCode" id="cb383"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb383-1"><a href="multilevel-modelling-practical-8-week-9.html#cb383-1" tabindex="-1"></a><span class="fu">anova</span>(betablok.glmer, betablok.glmer2)</span></code></pre></div>
<pre><code>## Data: betablok
## Models:
## betablok.glmer: cbind(r, (n - r)) ~ treat + (1 | center)
## betablok.glmer2: cbind(r, (n - r)) ~ treat + (treat | center)
##                 npar    AIC    BIC  logLik deviance  Chisq Df Pr(&gt;Chisq)
## betablok.glmer     3 324.42 329.77 -159.21   318.42                     
## betablok.glmer2    5 327.65 336.58 -158.83   317.65 0.7661  2     0.6818</code></pre>
We have insufficient evidence to reject the null hypothesis that the random slope variance is zero. We don’t need the random slopes.
</details>
<p><span class="math inline">\(~\)</span></p>
<p>Inspect the random intercept and slope values for <code>betablok.glmer2</code> (using <code>plot_model</code>):</p>
<div class="sourceCode" id="cb385"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb385-1"><a href="multilevel-modelling-practical-8-week-9.html#cb385-1" tabindex="-1"></a><span class="fu">require</span>(sjPlot)</span>
<span id="cb385-2"><a href="multilevel-modelling-practical-8-week-9.html#cb385-2" tabindex="-1"></a><span class="fu">plot_model</span>(betablok.glmer2, <span class="at">type=</span><span class="st">&quot;re&quot;</span>)</span></code></pre></div>
<p><img src="MLM_worksheets_files/figure-html/unnamed-chunk-182-1.png" width="672" /></p>
<p>What can you say about the random treatment slopes?</p>
<p><span class="math inline">\(~\)</span></p>
<p>Let’s do some additional diagnostic checking for the random intercept and slope model. Start with diagnostics for the random effects:</p>
<div class="sourceCode" id="cb386"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb386-1"><a href="multilevel-modelling-practical-8-week-9.html#cb386-1" tabindex="-1"></a><span class="fu">qqnorm</span>(<span class="fu">ranef</span>(betablok.glmer2)<span class="sc">$</span>center[[<span class="dv">1</span>]]) <span class="co">#random intercepts</span></span>
<span id="cb386-2"><a href="multilevel-modelling-practical-8-week-9.html#cb386-2" tabindex="-1"></a><span class="fu">qqline</span>(<span class="fu">ranef</span>(betablok.glmer2)<span class="sc">$</span>center[[<span class="dv">1</span>]])</span></code></pre></div>
<p><img src="MLM_worksheets_files/figure-html/unnamed-chunk-183-1.png" width="672" /></p>
<div class="sourceCode" id="cb387"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb387-1"><a href="multilevel-modelling-practical-8-week-9.html#cb387-1" tabindex="-1"></a><span class="fu">qqnorm</span>(<span class="fu">ranef</span>(betablok.glmer2)<span class="sc">$</span>center[[<span class="dv">2</span>]]) <span class="co">#random slopes</span></span>
<span id="cb387-2"><a href="multilevel-modelling-practical-8-week-9.html#cb387-2" tabindex="-1"></a><span class="fu">qqline</span>(<span class="fu">ranef</span>(betablok.glmer2)<span class="sc">$</span>center[[<span class="dv">2</span>]])</span></code></pre></div>
<p><img src="MLM_worksheets_files/figure-html/unnamed-chunk-183-2.png" width="672" /></p>
<p><strong>TASK:</strong> What is your overall conclusion?</p>
<details>
<summary>
Click for solution
</summary>
<p>Including random slopes does not seem worthwhile. This conclusion is supported by AIC, the likelihood ratio test and the plot of the fitted random slope effects (which are very similar, suggesting very small variance).</p>
Overall, the combined studies point towards a small reduction of death risk due to the use betablockers.
</details>
<p><span class="math inline">\(~\)</span></p>
</div>
<div id="exercise-3-optional-toxoplasmosis-data-revisited" class="section level2 hasAnchor" number="8.5">
<h2><span class="header-section-number">8.5</span> Exercise 3 (optional): Toxoplasmosis data revisited<a href="multilevel-modelling-practical-8-week-9.html#exercise-3-optional-toxoplasmosis-data-revisited" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>We revisit the Toxoplasmosis (rainfall) data from the previous practical. We load and prepare the data frame as previously.</p>
<div class="sourceCode" id="cb388"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb388-1"><a href="multilevel-modelling-practical-8-week-9.html#cb388-1" tabindex="-1"></a><span class="fu">require</span>(npmlreg)</span>
<span id="cb388-2"><a href="multilevel-modelling-practical-8-week-9.html#cb388-2" tabindex="-1"></a><span class="fu">data</span>(rainfall)</span>
<span id="cb388-3"><a href="multilevel-modelling-practical-8-week-9.html#cb388-3" tabindex="-1"></a>rainfall<span class="sc">$</span>x <span class="ot">&lt;-</span> rainfall<span class="sc">$</span>Rain<span class="sc">/</span><span class="dv">1000</span></span></code></pre></div>
<p>We had fitted the following two logistic models, and identified some superiority of the cubic over the linear moodel.</p>
<div class="sourceCode" id="cb389"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb389-1"><a href="multilevel-modelling-practical-8-week-9.html#cb389-1" tabindex="-1"></a>toxo.glm <span class="ot">&lt;-</span> <span class="fu">glm</span>(<span class="fu">cbind</span>(Cases,Total<span class="sc">-</span>Cases) <span class="sc">~</span> x, </span>
<span id="cb389-2"><a href="multilevel-modelling-practical-8-week-9.html#cb389-2" tabindex="-1"></a>  <span class="at">family=</span><span class="fu">binomial</span>(<span class="at">link=</span>logit), <span class="at">data=</span>rainfall)</span>
<span id="cb389-3"><a href="multilevel-modelling-practical-8-week-9.html#cb389-3" tabindex="-1"></a><span class="fu">summary</span>(toxo.glm)</span></code></pre></div>
<pre><code>## 
## Call:
## glm(formula = cbind(Cases, Total - Cases) ~ x, family = binomial(link = logit), 
##     data = rainfall)
## 
## Coefficients:
##             Estimate Std. Error z value Pr(&gt;|z|)
## (Intercept)   0.3424     0.8522   0.402    0.688
## x            -0.1562     0.4428  -0.353    0.724
## 
## (Dispersion parameter for binomial family taken to be 1)
## 
##     Null deviance: 74.212  on 33  degrees of freedom
## Residual deviance: 74.087  on 32  degrees of freedom
## AIC: 168.78
## 
## Number of Fisher Scoring iterations: 3</code></pre>
<div class="sourceCode" id="cb391"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb391-1"><a href="multilevel-modelling-practical-8-week-9.html#cb391-1" tabindex="-1"></a>toxo3.glm <span class="ot">&lt;-</span> <span class="fu">glm</span>(<span class="fu">cbind</span>(Cases,Total<span class="sc">-</span>Cases) <span class="sc">~</span> x<span class="sc">+</span><span class="fu">I</span>(x<span class="sc">^</span><span class="dv">2</span>)<span class="sc">+</span><span class="fu">I</span>(x<span class="sc">^</span><span class="dv">3</span>),</span>
<span id="cb391-2"><a href="multilevel-modelling-practical-8-week-9.html#cb391-2" tabindex="-1"></a>  <span class="at">family=</span><span class="fu">binomial</span>(<span class="at">link=</span>logit), <span class="at">data=</span>rainfall)</span>
<span id="cb391-3"><a href="multilevel-modelling-practical-8-week-9.html#cb391-3" tabindex="-1"></a><span class="fu">summary</span>(toxo3.glm)</span></code></pre></div>
<pre><code>## 
## Call:
## glm(formula = cbind(Cases, Total - Cases) ~ x + I(x^2) + I(x^3), 
##     family = binomial(link = logit), data = rainfall)
## 
## Coefficients:
##             Estimate Std. Error z value Pr(&gt;|z|)    
## (Intercept)  -290.17      87.22  -3.327 0.000878 ***
## x             449.98     134.70   3.341 0.000836 ***
## I(x^2)       -231.13      69.03  -3.348 0.000813 ***
## I(x^3)         39.32      11.74   3.351 0.000806 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## (Dispersion parameter for binomial family taken to be 1)
## 
##     Null deviance: 74.212  on 33  degrees of freedom
## Residual deviance: 62.635  on 30  degrees of freedom
## AIC: 161.33
## 
## Number of Fisher Scoring iterations: 3</code></pre>
<p>Endorse this result by applying <code>anova</code> onto this pair of models:</p>
<div class="sourceCode" id="cb393"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb393-1"><a href="multilevel-modelling-practical-8-week-9.html#cb393-1" tabindex="-1"></a><span class="fu">anova</span>(toxo.glm,toxo3.glm,<span class="at">test=</span><span class="st">&quot;LRT&quot;</span>)</span></code></pre></div>
<pre><code>## Analysis of Deviance Table
## 
## Model 1: cbind(Cases, Total - Cases) ~ x
## Model 2: cbind(Cases, Total - Cases) ~ x + I(x^2) + I(x^3)
##   Resid. Df Resid. Dev Df Deviance Pr(&gt;Chi)   
## 1        32     74.087                        
## 2        30     62.635  2   11.453 0.003259 **
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
<p>In the previous practical we already expressed some suspicion about the relevance of the cubic term: While statistically significant, is it “really there”, or are we “overfitting” a random feature of this data?</p>
<p>In this connection it is worth recalling a basic feature of the Binomial model: It is a one-parameter distribution, with a fixed mean-variance relationship (just as the Poisson model, but unlike the Normal or Gamma model) and with no scale parameter to absorb “excess variability”. If the data possess more inherent variability than this rigid mean-relationship allows, one speaks of “overdispersion”.</p>
<p>It turns out that one way of addressing this problem is two consider the data set “artificially” as a two-level model, i.e. to introduce a random effect for the “upper level” which however coincides with the observation index (Aitkin et al, Statistical Modelling in R, page Sec 8.4.3.). That is, each observation
gets assigned its own random effect, which then can absorb the excess variation. Create a vector of observation ID’s,</p>
<div class="sourceCode" id="cb395"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb395-1"><a href="multilevel-modelling-practical-8-week-9.html#cb395-1" tabindex="-1"></a>rainfall<span class="sc">$</span>ID <span class="ot">&lt;-</span> <span class="dv">1</span><span class="sc">:</span><span class="dv">34</span></span></code></pre></div>
<p>and then fit an “empty” model only containing the random effect for the IDs, that is <code>(1|D)</code>.</p>
<div class="sourceCode" id="cb396"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb396-1"><a href="multilevel-modelling-practical-8-week-9.html#cb396-1" tabindex="-1"></a>toxo.glmm3 <span class="ot">&lt;-</span> <span class="fu">glmer</span>(<span class="fu">cbind</span>(Cases,Total<span class="sc">-</span>Cases) <span class="sc">~</span> (<span class="dv">1</span><span class="sc">|</span>ID),</span>
<span id="cb396-2"><a href="multilevel-modelling-practical-8-week-9.html#cb396-2" tabindex="-1"></a>  <span class="at">family=</span>binomial, <span class="at">data=</span>rainfall)</span>
<span id="cb396-3"><a href="multilevel-modelling-practical-8-week-9.html#cb396-3" tabindex="-1"></a><span class="fu">summary</span>(toxo.glmm3)</span></code></pre></div>
<pre><code>## Generalized linear mixed model fit by maximum likelihood (Laplace Approximation) [&#39;glmerMod&#39;]
##  Family: binomial  ( logit )
## Formula: cbind(Cases, Total - Cases) ~ (1 | ID)
##    Data: rainfall
## 
##      AIC      BIC   logLik deviance df.resid 
##    154.6    157.7    -75.3    150.6       32 
## 
## Scaled residuals: 
##      Min       1Q   Median       3Q      Max 
## -1.26132 -0.82407 -0.04503  0.40309  1.32907 
## 
## Random effects:
##  Groups Name        Variance Std.Dev.
##  ID     (Intercept) 0.2634   0.5132  
## Number of obs: 34, groups:  ID, 34
## 
## Fixed effects:
##             Estimate Std. Error z value Pr(&gt;|z|)
## (Intercept)  -0.1229     0.1381   -0.89    0.374</code></pre>
<p>We see that this model leads to a lower AIC than any of the models considered previously!</p>
<p>We conclude that there is no actual dependency of toxoplasmosis rates on rainfall, and that the observed cubic trend has been due to unexplained excess variability (=overdispersion).</p>
<p><span class="math inline">\(~\)</span></p>
</div>
<div id="summative-assessment" class="section level2 hasAnchor" number="8.6">
<h2><span class="header-section-number">8.6</span> Summative assessment<a href="multilevel-modelling-practical-8-week-9.html#summative-assessment" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>If there is still time remaining, please use this to work on your summative assessment.</p>
</div>
<div id="end-of-lab-2" class="section level2 hasAnchor" number="8.7">
<h2><span class="header-section-number">8.7</span> ## End of lab!<a href="multilevel-modelling-practical-8-week-9.html#end-of-lab-2" class="anchor-section" aria-label="Anchor link to header"></a></h2>

</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="multilevel-modelling-practical-7-week-8.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="multilevel-modelling-practical-9-week-10.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": false,
"twitter": false,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"whatsapp": false,
"all": false
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": null,
"text": null
},
"history": {
"link": null,
"text": null
},
"view": {
"link": null,
"text": null
},
"download": null,
"search": {
"engine": "fuse",
"options": null
},
"toc": {
"collapse": "section",
"scroll_highlight": true,
"search": true,
"sidebar": true
}
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.9/latest.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
